### ISSUE TITLE
Add a scroll to top button in the homepage

### ISSUE THREAD

**Issue by m-code12** [garg3133/JagratiWebApp#100]

**Comment by garg3133** [comment]
Yeah, having a scroll-to-top button would be nice. Assigning you the issue.

**Comment by Abhijay007** [comment]
@garg3133 is someone working on it? can I work on it?

**Comment by m-code12** [comment]
Yes I am working on it @Abhijay007

**Comment by Abhijay007** [comment]
> Yes I am working on it @Abhijay007

ok @m-code12 👍
