### ISSUE TITLE
Creation of issue, pr templates

### ISSUE THREAD

**Issue by Sloth-Panda** [garg3133/JagratiWebApp#101]
Let me know if there is any requirement of issue and pr templates

**Comment by garg3133** [comment]
There is already an open issue #40 and an open PR #83 for this. I had some doubts and required some changes in that. You can ask in that issue if he is still interested in solving this issue otherwise you can take that issue.

**Comment by Sloth-Panda** [comment]
@garg3133 can you tell me whats the problem that you have not merged that code cause its been 11days since his code is not merged so can I just go ahead and make the pr?

**Comment by garg3133** [comment]
The PR looks good to me. I was just confused about one thing which you can read in the PR review comment.
