### ISSUE TITLE
Add a github link logo at the footer to navigate open source devs to the github repository

### ISSUE THREAD

**Issue by lopeselio** [garg3133/JagratiWebApp#103]
This can help in the development of the project in the future

**Comment by garg3133** [comment]
That's a great idea @lopeselio! Thanks for suggesting.

**Comment by MASTERCHIEF011** [comment]
can u assign this to me.

**Comment by lopeselio** [comment]
Hey I had been working on this already

**Comment by Aayush-hub** [comment]
@garg3133 Can you assign me this if its open?

**Comment by garg3133** [comment]
I don't think @lopeselio is working on this. So, go ahead @Aayush-hub! Assigning it to you.
