### ISSUE TITLE
Refactor the Errors observed in Flake8 linter

### ISSUE THREAD

**Issue by vybhav72954** [garg3133/JagratiWebApp#105]
I ran the Flake8 linter on the whole codebase.

Here is the [instance](https://github.com/garg3133/JagratiWebApp/pull/104/checks?check_run_id=1888095595).

There are approximately 50 errors.

I believe we should start sorting them like right now before the numbers start piling up.

Moreover, we need to consider that flake8 is a compromising linter unlike PyLint, I understand that the errors *might* not be breaking, but I believe it's always a good idea to get rid of them.

**Comment by vybhav72954** [comment]
Reference #104

**Comment by garg3133** [comment]
Yeah, we should definitely fix them and have some proper coding standards in place moving forward. Would you like to work on this too?

**Comment by vybhav72954** [comment]
I can start with refactoring the errors like right now

**Comment by vybhav72954** [comment]
For guidelines, I can create more of a vague kind of styling, like all the basic guidelines without nitpicking obviously.

later on, we can discuss what we want to edit.

**Comment by vybhav72954** [comment]
@garg3133 It would take time to make a Guideline though, so with this issue, I am just refactoring the code :)

Can I have a SWOC too, please

**Comment by garg3133** [comment]
I'll be refactoring the codebase myself. Thank you for your time and efforts.
