### ISSUE TITLE
Adding Docker Support: 

### ISSUE THREAD

**Issue by DanBrown47** [garg3133/JagratiWebApp#110]
**Is your feature request related to a problem? Please describe.**
Not related to a problem but is an enhancement

**Describe the solution you'd like**
I would like to add docker support for Jagrati App enabling much more support for developers as they need not setup python environment manually to test also cloud deployment will become more simple.

**Describe alternatives you've considered**
Adding docker support and docker ignore files

**Additional context**
[About docker](https://www.youtube.com/watch?v=eGz9DS-aIeY)
[Why docker is essential for web apps - public forumn](https://www.quora.com/Why-should-I-use-Docker-for-my-web-app)

**Comment by DanBrown47** [comment]
Permission to contribute

**Comment by garg3133** [comment]
That sounds great @DanBrown47! You can surely work on this issue. Assigning it to you.

**Comment by garg3133** [comment]
Resolved in #111.
