### ISSUE TITLE
README.md file enhancement

### ISSUE THREAD

**Issue by anirudhsai20** [garg3133/JagratiWebApp#114]
The README.md file can be enhanced by adding a list of all the open source programs that this project has been listed in. A table of all the contributors will further enhance the file.

**Comment by anirudhsai20** [comment]
Hi @garg3133 . Can I please work on this under SWOC?

**Comment by garg3133** [comment]
Sure @anirudhsai20, you can work on this. Assigning it to you.

Open Source Program we participated in:
* Kharagpur Winter of Code 2020
* Script Winter of Code
* Mexili Winter of Code

**Comment by chehak123** [comment]
Hi, i want to contribute as a participant of gssoc'21

**Comment by garg3133** [comment]
@chehak123 Please wait for a while till we get proper instructions from the administrators of the program on how to move forward.

**Comment by nilisha-jais** [comment]
I want to work on it

**Comment by garg3133** [comment]
Sure @nilisha-jais, you can take this issue. Assigning it to you.

**Comment by Naman-12911** [comment]
I want to update read me file . I am a participant of girls scripts summer of code

**Comment by garg3133** [comment]
@Naman-12911, @nilisha-jais is currently working on this issue. You can take some other issue and work on that.

**Comment by Naman-12911** [comment]
ohk sir.

**Comment by vismitap** [comment]
May I work on this as a part of GSSoC'21?

**Comment by garg3133** [comment]
@vismitap, @nilisha-jais currently has a PR #138 open for this on which I requested some changes. If she does not respond by tomorrow, I'll assign it to you.

BTW, what happened with the issue #78 you were working on earlier? I thought you learnt testing.

**Comment by vismitap** [comment]
> @vismitap, @nilisha-jais currently has a PR #138 open for this on which I requested some changes. If she does not respond by tomorrow, I'll assign it to you.
> 
> BTW, what happened with the issue #78 you were working on earlier? I thought you learnt testing.

Yeah sorry! I had my exams, so could not contribute. Still did not learn it completely. Got some basic idea though. Will learn from where I left and give issues related to testing a try again very soon. 😇✌

**Comment by garg3133** [comment]
As @nilisha-jais is not responding, @vismitap you can take this issue.

**Comment by vismitap** [comment]
> As @nilisha-jais is not responding, @vismitap you can take this issue.

Yes, thank you!
