### ISSUE TITLE
Remove "Update" logic in student attendance.

### ISSUE THREAD

**Issue by garg3133** [garg3133/JagratiWebApp#118]
Remove the "Update" button and its logic in Student attendance view.

**Comment by garg3133** [comment]
@sagarpandyansit ^

**Comment by subhangi2731** [comment]
can you please assign this to me?

**Comment by tanya1810** [comment]
Hii. You can check my profile. I have worked on several Django project. I can resolve this issue. Please assign this issue to me. @garg3133

**Comment by sagarpandyansit** [comment]
@subhangi2731 @tanya1810, I am working on it.

**Comment by garg3133** [comment]
No worries @tanya1810, I'll open up few more issues which you can work on a :)
Just give me some time.

**Comment by garg3133** [comment]
Resolved in #142.
