### ISSUE TITLE
[feature]: Online Payment Integration 

### ISSUE THREAD

**Issue by amangupta37** [garg3133/JagratiWebApp#119]
### Integrating online payment option for better user experience to donate an amount  for the organization

**Comment by amangupta37** [comment]
> ### Integrating online payment option for better user experience to donate an amount for the organization

**Comment by amangupta37** [comment]
i would like to work on this feature

**Comment by garg3133** [comment]
Sure @amangupta37, that'll be a good idea. You can work on this. Assigning you the issue.

**Comment by ashutoshkrris** [comment]
I have also worked with Paytm and RazorPay integration in Django and want to work on this issue.

**Comment by garg3133** [comment]
@ashutoshkrris, @amangupta37 is working on this issue at this point. You can check with other issues if any interests you.

**Comment by ashutoshkrris** [comment]
Thanks @garg3133 
Let me know @amangupta37 , if you are not able to do this at any point of time.

**Comment by amangupta37** [comment]
@garg3133 since the backend is on python so I could not able to continue with this feature because I m experienced with Node.js for backend dev. You may assign this issue to @ashutoshkrris

**Comment by ashutoshkrris** [comment]
> @garg3133 since the backend is on python so I could not able to continue with this feature because I m experienced with Node.js for backend dev. You may assign this issue to @ashutoshkrris

Thanks !
@garg3133 let me know if I can work on this issue. Also, please mention which payment gateway you wish to integrate.

**Comment by garg3133** [comment]
Sure @ashutoshkrris, you can work on this. I think integrating Paytm gateway would be fine.

**Comment by ashutoshkrris** [comment]
Sure, I'll work on it.
Thanks

**Comment by ashutoshkrris** [comment]
Hey @garg3133 
I have integrated Paytm. Please check the demo video attached below and let me know if you find any issue with it.

https://user-images.githubusercontent.com/47353498/110837765-ac8da980-82c7-11eb-881f-97dfd56020ee.mp4

**Comment by garg3133** [comment]
Seems good @ashutoshkrris! Can you change the wording at a few places? Like instead of "Pay", write "Donate Now" and the button should be present in the first section, just below the bank details.

Also, in the modal opened, it is not clear whose name and email it is asking. So, you can write "Donator's Name" and "Donator's Email". Also, change the title of the modal to something like "Donation Details"... you must have got the idea.

**Comment by ashutoshkrris** [comment]
Yeah , sure @garg3133 
I'll do it.

**Comment by ashutoshkrris** [comment]
@garg3133 I've made the PR
