### ISSUE TITLE
Update UI

### ISSUE THREAD

**Issue by tmo66** [garg3133/JagratiWebApp#12]
Current UI looks old.

- [ ] Update Navigation Bar

- [ ] Update Show-Case

- [ ] Update About Us

- [ ] Update Initiatives

**Comment by tmo66** [comment]
I want to work on this, can I?

**Comment by garg3133** [comment]
Yeah @tmo66, sure!!

**Comment by isha27255** [comment]
Can I work on this ?

**Comment by garg3133** [comment]
@tmo66 has a better idea of this issue. Tushar, can you please help her with the issue?

**Comment by tmo66** [comment]
Yeah Sure. @isha27255 Join the [Discord Server](https://discord.gg/Thu4xHRs), I will explain to you there about the new theme!

**Comment by roli25** [comment]
can I work on this?

**Comment by tmo66** [comment]
Yeah Sure!!

**Comment by MayankGeek** [comment]
Can I work on this?

**Comment by Isha77agarwal** [comment]
I want to work on its UI

**Comment by 07yuvraj** [comment]
i also want on this issue

**Comment by garg3133** [comment]
This issue doesn't provide much context on what to do. Closing it for now.

@tmo66 You may open separate issues for UI update with well-defined tasks.
