### ISSUE TITLE
[feature]: Allow to change student profile picture

### ISSUE THREAD

**Issue by garg3133** [garg3133/JagratiWebApp#120]
**Is your feature request related to a problem? Please describe.**
Currently, there is no option of updating the profile picture of students.

**Describe the solution you'd like**
On clicking over the profile picture of a student on student profile update page (/students/profile/update/1), a popover should appear (see Bootstrap Popovers) with two options, one for viewing the profile picture which should open the profile picture in a new tab and the other one to update the profile picture which should ask the user to select an image from computer and should update the image upon successful selection.

**Comment by micksharma** [comment]
I want to work on this issue.

**Comment by anurag0singh** [comment]
Sir assign me this issue under GSSOC'21

**Comment by thesakshipandey** [comment]
I can work on this issue
please assign me this issue under GSSoC'21

**Comment by thesakshipandey** [comment]
I tried taking up the issues, which I could do, but most of them are assigned anyway.
Okay, if anyone is not able to, then I'll do it for sure!
