### ISSUE TITLE
Add checks for profile picture while uploading

### ISSUE THREAD

**Issue by garg3133** [garg3133/JagratiWebApp#121]
While uploading a profile picture on `Complete Profile` page, add checks to verify that the entity being uploaded is actually an image file (has `.jpg`, `.jpeg`, `.png` or `.gif` extension) and not some random file. 

The form should show an error (can be a JS alert) if any random file is selected to be uploaded instead of an image file.

**Comment by somya51p** [comment]
Hello, @garg3133 sir! I wish to contribute to this issue under gssoc'21.

**Comment by garg3133** [comment]
Sure @somya51p, go ahead! Assigning you the issue.

**Comment by sahildotexe** [comment]
Hey !! I am a participant of GSSOC'21 , can you assign this issue to me?

**Comment by tmo66** [comment]
It's great to see your enthusiasm @sahildotexe, but right now @somya51p is working on this. You can check other issues for now.

**Comment by Naman-12911** [comment]
hello please assign me this issue under the GSSOC.

**Comment by Aarti002** [comment]
hello @garg3133 can i take this issue as a gssoc participant

**Comment by garg3133** [comment]
@Naman-12911 @Aarti002 All the issues which are already assigned were assigned today only. You can check with other issues which are currently unassigned.

**Comment by garg3133** [comment]
Resolved in #130.
