### ISSUE TITLE
Display subject on dashboard.

### ISSUE THREAD

**Issue by garg3133** [garg3133/JagratiWebApp#123]
Display the subject that was scheduled to be taught on the selected day for the selected section on Dashboard.

The subject should be displayed as "**Subject scheduled:** <subject_name>" below the Continue button and above the classwork-homework on the dashboard.

The subject can be retrieved from the `Schedule` table in `home` app.

**Comment by micksharma** [comment]
I want to work on this issue.

**Comment by akshay399** [comment]
Can i please work on this issue?

**Comment by garg3133** [comment]
Sure @akshay399, you can work on this. Assigning you the issue.

**Comment by Aarti002** [comment]
cool , thanks!!

**Comment by akshay399** [comment]
> Sure @akshay399, you can work on this. Assigning you the issue.

pls review the PR, thanks

**Comment by garg3133** [comment]
Resolved in #170.
