### ISSUE TITLE
Add "Subject Taught" field in classwork-homework

### ISSUE THREAD

**Issue by garg3133** [garg3133/JagratiWebApp#131]
Add a `subject_taught` field in classwork-homework model. This is important because sometimes some other subject is taught to the students than what was actually scheduled.

For filling this field, there should be a `select` input in Update CW-HW section of the dashboard which. Initially, the value of select input should be the subject which was actually scheduled to be taught, which the user can change later on and can save it by submitting the form.

**Comment by garg3133** [comment]
@tanya1810 Would you like to work on this?

**Comment by tanya1810** [comment]
Yes sir. I will do this.

**Comment by garg3133** [comment]
Let me know if you face any difficulty.

**Comment by tanya1810** [comment]
Sure. Thanks a lot :)

**Comment by garg3133** [comment]
Duplicate of #176.
