### ISSUE TITLE
[feature]: enhance navbar

### ISSUE THREAD

**Issue by Kritikaagra** [garg3133/JagratiWebApp#132]
Hey!
I would like to enhance the navbar as it makes a better user experience
please assign this to me under ggsoc'21

**Comment by garg3133** [comment]
@Kritikaagra Can you please explain in more details how you are going to enhance the navbar?

**Comment by thesakshipandey** [comment]
I can do this using Bootstrap, Can you assign me this issue under GSSoC'21?

**Comment by garg3133** [comment]
Okay @Kritikaagra, you can go ahead.

**Comment by garg3133** [comment]
@thesakshipandey We need some changes in the sidebar of the dashboard (which appears after logging in). What we want is to have the links to all the different pages on the application placed there in categories. Would you like to do that?

**Comment by thesakshipandey** [comment]
Yeah, sure
Please assign that issue under GSSoC'21
I would do it!!!

**Comment by Priyanka7011** [comment]
Hii ! I am a GSSOC 2021 participant!
I would also like to give designs for the navbar and footer. If you like it @garg3133 please merge it.
Thank You!!!

**Comment by tmo66** [comment]
@Priyanka7011, @Kritikaagra is already working on it. You can check out other unassigned issues for now,
