### ISSUE TITLE
Add links to all the different pages on sidebar

### ISSUE THREAD

**Issue by garg3133** [garg3133/JagratiWebApp#133]
We need to have the links to all of the different pages available throughout the application placed on the sidebar, in categories. For example, there should be a collapsible/dropdown with name `Students` and on opening it, links to all the pages related to students should appear (like `All students`, `Add new student`, `Student Attendance`, etc.).

The sidebar appears on almost all the pages after logging into the application.

**Comment by garg3133** [comment]
@thesakshipandey ^

**Comment by thesakshipandey** [comment]
Thanks I will do it!!

**Comment by garg3133** [comment]
I'm currently thinking of 4 categories:
1. Manage Classes: Dashboard, Volun. Schedule
2. Students: All students, Add new student, Take Attendance
3. Volunteers: All volunteers, Attendance
4. Self: Update Schedule, Update Profile

**Comment by hi-18-K** [comment]
I am GSSoC participant. I have worked on this kind of feature so can do it. Could you assign this to me?


Also, I have one query.. These tables 'students', 'volunteers', 'self' already exist in database? and we have to fetch data only? or we need to create the whole functionality..?

**Comment by garg3133** [comment]
Hey @hi-18-K, @thesakshipandey is working on it right now. You can take some other issue and if you don't find any, let me know your skill-set and I'll create one for you.

**Comment by thesakshipandey** [comment]
So the self part is already done?
I have do the other 3 right?
First I'll make the student one!!

**Comment by garg3133** [comment]
Yeah, self part is already there but it is not properly categorised. So, you need to create a category dropdown for Self as well.

**Comment by thesakshipandey** [comment]
![image](https://user-images.githubusercontent.com/54810583/110760540-d23d9300-8274-11eb-824a-245730b7fc8b.png)
somewhat like this right? 

I'll make it look better :)

**Comment by garg3133** [comment]
Instead of dropdown, try using Bootstrap Collapse.

**Comment by thesakshipandey** [comment]
ok sir
I was thinking of collapse only, but you said dropdown, so I went for dropdown

**Comment by thesakshipandey** [comment]
![image](https://user-images.githubusercontent.com/54810583/110761412-b686bc80-8275-11eb-815b-fdeb81d0622e.png)
anyway I did this w dropdown itself though >>

**Comment by thesakshipandey** [comment]
I'll change it!

**Comment by simranbhalla3** [comment]
Hi I am a Gssoc'21 participant and would like to work on this issue .

**Comment by coding-geek21** [comment]
@garg3133  Can I work on this issue?

**Comment by garg3133** [comment]
Resolved in 8c185e4.
