### ISSUE TITLE
Update contributing.md

### ISSUE THREAD

**Issue by khareyash05** [garg3133/JagratiWebApp#139]
I would like to update contributing.md specifying not just cloning and forking the repo but also how to update your local and forked repo when there are changes in the upstream, synchronizing the fork,creating a new branch for each issue,squashing your commits 
I would like to work in it as a part of GSSOC'21

**Comment by garg3133** [comment]
That would be great @khareyash05, go ahead! Assigning you the issue.

**Comment by khareyash05** [comment]
@garg3133  created a PR Have a look

**Comment by khareyash05** [comment]
@garg3133 Have a look
