### ISSUE TITLE
Fetch initiatives from database on landing page

### ISSUE THREAD

**Issue by garg3133** [garg3133/JagratiWebApp#14]
Instead of putting the content of different initiatives in HTML file, we should instead fetch the initiatives from the database.

For doing this, create a new model in `misc` app with name `Initiative` and the following fields:
- `title` (Initiative title)
- `description` (Initiative Description)
- `thumbnail` (Initiative Thumbnail)

After creating the model, register the model in `admin.py` so that the initiatives content can be updated through Admin Panel.

And then at last, fetch the initiatives from the database on the landing page.

Feel free to ping me here if you are stuck somewhere :)

**Comment by dennis-pg** [comment]
Would like to work on this

**Comment by garg3133** [comment]
Sure @dennis-pg, you can move ahead.

**Comment by AshishMhrzn10** [comment]
want to work in it .please assign.

**Comment by rachitmanas** [comment]
Can I work on this issue?

**Comment by garg3133** [comment]
@dennis-pg You are working on this, right?

**Comment by garg3133** [comment]
Ok then, as @dennis-pg is not responding, @rachitmanas you can take up this issue.

**Comment by ChiragSharma1** [comment]
Can i work on this?

**Comment by garg3133** [comment]
Yes, sure! Go ahead.

Ping me if you are stuck anywhere.

**Comment by ChiragSharma1** [comment]
@garg3133  if i make models in models.py file of home app ,i think that will work much better as index.html is called via home app,
is this what i am thinking is correct?

**Comment by garg3133** [comment]
Yeah, I agree, it will be much easier that way but I wish to keep the home app clean and only for important stuff related to classes. Having unrelated models in home app can make it cluttered.

**Comment by ChiragSharma1** [comment]
@garg3133  Ok fine , i will be doing there only, 
Than I think we also have to create urls.py in misc app ,
is this correct or not ?

**Comment by garg3133** [comment]
No, creating urls.py in misc app is not required for now.

**Comment by ChiragSharma1** [comment]
Than from where we have to call the view which  is we have to make in views.py in misc app

**Comment by garg3133** [comment]
@ChiragSharma1 What is the status of your work?

**Comment by tmo66** [comment]
Can I work on this? I will do this with issue #39

**Comment by garg3133** [comment]
Sure thing @tmo66.

**Comment by garg3133** [comment]
Till when can I expect it to be complete @tmo66?

**Comment by promaroy** [comment]
Can I work on this as a part of GSSOC '21?

**Comment by micksharma** [comment]
Can I work on this issue.

**Comment by garg3133** [comment]
Sure @promaroy, go ahead! Assigning you the issue.

**Comment by promaroy** [comment]
@garg3133 for thumbnail do I need to keep an upload option for image? Or can we give the link for images?

**Comment by garg3133** [comment]
@promaroy Giving the upload option would be better.
