### ISSUE TITLE
Navbar and footer can be improved

### ISSUE THREAD

**Issue by Priyanka7011** [garg3133/JagratiWebApp#140]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

Hii I am a GSSOC 2021 participant.
I think navbar and footer can be improved. I am a UI/UX designer .
I will put my best efforts.
Please assign me this task.
I would love to contribute to this wonderful project .
Thank You !!

**Additional context**

**Comment by garg3133** [comment]
Hey @Priyanka7011, thanks for raising this issue. There's already an issue open for this: #132. If you like, you can create the design of what you are proposing and post it there on the issue and I'll assign that issue to you if I like your designs more.

Closing this issue as a duplicate.
