### ISSUE TITLE
[feature]:

### ISSUE THREAD

**Issue by Naman-12911** [garg3133/JagratiWebApp#146]
#The problem 
When a person sign up in our website its ohk. But when a bot sign up itself by different email address its creates problem and our server is also crash because of bots sin up.
# The solution.
we to apply a google re Captcha to protect from bots in our sin up page with the google security.
 # feature 
I want to develop this feature in the sin up page .
kindly assign me this issue under GSSOC

**Comment by Naman-12911** [comment]
> Hi! Thanks for opening your first issue at JagratiWebApp 🚀 We really appreciate it. 🙌

Thanks you are assign me?

**Comment by garg3133** [comment]
Hey @Naman-12911, thanks for raising this issue. But the problem with this solution is that even if we use re-Captcha, the attacker may still use our open APIs for this, which is even easier to use than using the UI for creating fake accounts. So, using a re-Captcha does not make sense here. We need to implement something in the backend for this like blocking the IP if too many account creation requests are being received from a single IP address or something of this sort.

**Comment by Naman-12911** [comment]
Ohk.
