### ISSUE TITLE
Replace the tech stack names with their logos 

### ISSUE THREAD

**Issue by rohank2502** [garg3133/JagratiWebApp#147]
I will like to add the logo of each tech stack used this will make our readme more attractive !! Will start working on It as soon as I get assigned !

**Comment by garg3133** [comment]
Sure @rohank2502, you can work on this. But make sure the icon size is not too big. Assigning you this issue.

**Comment by rohank2502** [comment]
> 
> 
> Sure @rohank2502, you can work on this. But make sure the icon size is not too big. Assigning you this issue.

Yes the icon are perfect in size !!

**Comment by tmo66** [comment]
Hey, @rohank2502 there is also a mistake in README(due to consistent modification). In line 99, it should be Line 30 and 31, instead of 27 and 28. Fix it too!

**Comment by rohank2502** [comment]
Yes sure I will get that too and will see if anything can be fixed and with
proper updation i will do that also
