### ISSUE TITLE
[bug]: Dropdown Navbar

### ISSUE THREAD

**Issue by tmo66** [garg3133/JagratiWebApp#152]
When the screen width is less than 760 px, the navbar hides, and the hamburger button appears, and on clicking on that, the navbar appears in a dropdown format.

**Issue**
The dropdown navbar is completely unsync with the full-screen Navbar.

**How to fix it?**
Remove the boundaries, change the hover option(make the background red and white text), and add some animation! Also, the hamburger button is an image, instead of that create it using HTML and CSS.

**Screenshots**
![Error](https://user-images.githubusercontent.com/63875632/111018737-9cb5b880-83e0-11eb-9897-61e702d476d3.PNG)

**Comment by Saatvik21** [comment]
Sir I would like to work on this issue.

Please assign this to me.

**Comment by tmo66** [comment]
Sure @Saatvik21 assigning you the issue!

Pro Tip: We are already working on Navbar #132, keep an eye on [PR 144](https://github.com/garg3133/JagratiWebApp/pull/144).

**Comment by Saatvik21** [comment]
Sir regarding this issue, Is this correct when hovering over a link in dropdown menu?

![redbg](https://user-images.githubusercontent.com/61618767/111028543-487cf980-841d-11eb-8efd-0acc1d492468.png)

**Comment by tmo66** [comment]
@Saatvik21 as this issue is outdated and you are working on #168. I'm closing this issue.
