### ISSUE TITLE
[bug]: [GSSoC'21] Problem in Readme.md

### ISSUE THREAD

**Issue by sonal251001** [garg3133/JagratiWebApp#156]
**Describe the bug**
Hey @garg3133 there is a small error in the readme.md . It is written we donate education . The correction would be "we provide education" I am a GSSoC participant . I would like you to assign this issue to me.
**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by tmo66** [comment]
Hey @sonal251001, for choosing our project, and opening an important issue! Can you fix all the typos in the README.md, like 

> 1 student `was` selected in....
> 4 student cleared `the` entrance...
> To actually send emails to real users, comment line 27 and uncomment line 28 in Jagrati/settings/development.py `(This should be line 30 and line 31)`

These are just a few examples, can you fix them all?

**Comment by sonal251001** [comment]
Yes I'll start working once it is assigned to me . If you are the mentor/admin please see to that. Thankyou.

**Comment by tmo66** [comment]
Okay, Assigning you!
