### ISSUE TITLE
Misprinting

### ISSUE THREAD

**Issue by ChiragSharma1** [garg3133/JagratiWebApp#16]
i think ',' should be there instead of ';'
![Screenshot (14)](https://user-images.githubusercontent.com/63919014/96328101-18dbe800-105d-11eb-80ae-fad57194da5c.png)

**Comment by ChiragSharma1** [comment]
can i correct that ?

**Comment by shivarajloni** [comment]
can i contribute.. as i am first-time

thank you!

**Comment by garg3133** [comment]
@ChiragSharma1 I don't think there's any mistake there. It's meant to be in that way only.

Closing this issue.
