### ISSUE TITLE
New Home Page!

### ISSUE THREAD

**Issue by tmo66** [garg3133/JagratiWebApp#160]
The current theme looks old. We are thinking about shifting it to a new theme

https://www.figma.com/proto/g83XJFmTssvU0qXBnlfIyO/Jagrati?node-id=0%3A3&scaling=scale-down-width

We will open few issues regarding the same.
In this issue, you have to create the home page till Initiatives (excluding) and should render this page at  '/new'. You should place all the images, files, everything in a separate folder in the template and static folder. Don't make any changes to the existing Home Page.

For this, a beginner-level knowledge of Django is required, with an experience in HTML, CSS, and JS.

We are open to all ideas, and every creative input. Feel free to share yours!

**Comment by simranbhalla3** [comment]
Hi I am a Gssoc'21 participant and would like to work on this issue , I have experience in css and js , please assign me this issue
