### ISSUE TITLE
Header logo  

### ISSUE THREAD

**Issue by n-coder2k** [garg3133/JagratiWebApp#161]
Logo is not placed in correct position.It should be in left corner but currently its present in right corner of the header.

I would like to work on this issue as GSSOC participant.

**Screenshots**
![Screenshot](https://user-images.githubusercontent.com/59041032/111064642-2944a180-84db-11eb-806e-c0f4f821abf5.png)

**Comment by garg3133** [comment]
And in what sense is that inorrect? @n-coder2k

**Comment by n-coder2k** [comment]
@garg3133 It should be present at left corner before the title "Jagriti".That would look better.

**Comment by tmo66** [comment]
Hey @n-coder2k, I'm glad that you choose our project to contribute, but right now we are fine with the logo position and don't wish to change it. You can look at other open issues to work upon.
Thanks
