### ISSUE TITLE
Real Time Chat Assistant Integration

### ISSUE THREAD

**Issue by amangupta37** [garg3133/JagratiWebApp#166]
Chat Assistant for solving the real-time query  for better user experience

**Comment by amangupta37** [comment]
i would like to work on this issue under gssoc 2021

**Comment by tmo66** [comment]
Hey @amangupta37, I'm glad that you choose our project, but if you look at the real-life implementation of our project then you will understand that our project is going to be used by our College students for the management of Jagrati, and implementing a Chatbot doesn't make much difference. I hope you understand, you can look at other unassigned issues for now.
(I'm Closing this issue)
