### ISSUE TITLE
Enhance Navbar.

### ISSUE THREAD

**Issue by tmo66** [garg3133/JagratiWebApp#168]
1. There are currently no transitions implemented on the navbar.
2. The positioning of the navbar on small screens is not absolute, so it pushes the showcase downward.
3. The navbar opened on clicking on the hamburger menu should have some transparency like before.

**Comment by tmo66** [comment]
@Saatvik21

**Comment by Saatvik21** [comment]
I would love to work on this issue. 

Kindly assign me.
