### ISSUE TITLE
Show camera icon overlay on hover

### ISSUE THREAD

**Issue by garg3133** [garg3133/JagratiWebApp#174]
Show a camera icon overlay while hovering over the profile image on Update Profile page for students (`students/profile/update/<id>/`). The hovering effect is to give a sort of feedback to the user that they can update the profile photo by clicking over it.

See the hovering effect on the images [here](https://bandhuodisha.in/#gallery) to get an idea of what we want as a final output.

**Comment by Priyanshi-Sharma-142** [comment]
@garg3133 I want to work on this issue please assign it to me

**Comment by Priyanshi-Sharma-142** [comment]
I'm a gssoc participant. I want to work on this issue. Can you please assign it to me @garg3133?

**Comment by garg3133** [comment]
Sure @Priyanshi-Sharma-142, go ahead! Assigning it to you.

**Comment by shitesh2607** [comment]
can I work on this issue?

**Comment by garg3133** [comment]
@Priyanshi-Sharma-142 Are you working on this?

**Comment by garg3133** [comment]
As @Priyanshi-Sharma-142 is not able to work on this issue right now, @shitesh2607 I'm assigning this issue to you.

**Comment by garg3133** [comment]
@shitesh2607 Any progress on this?

**Comment by kirtilodha** [comment]
I want to work on this. Please assign it to me

**Comment by garg3133** [comment]
Sure @kirtilodha, go ahead! Assigning this to you.

**Comment by kirtilodha** [comment]
I've already solved the issue. Waiting for it to get reviewed.
