### ISSUE TITLE
Mark the status of homework of students

### ISSUE THREAD

**Issue by garg3133** [garg3133/JagratiWebApp#175]
Just like we take student attendance, we need to keep a record of whether the student completed his/her homework or not. For this, we can have checkboxes alongside each student name on the dashboard (just like we have on the student attendance page) showing whether the student did his/her homework or not. Along with that, the checkboxes can also be toggled to mark or unmark the homework status of the student.

This needs to be implemented on the Dashboard page using AJAX. You can refer to the working of student attendance for this as the implementation will be quite similar.

**Comment by sk1122** [comment]
I would like to implement this issue.

**Comment by AJAYSHARMA2012** [comment]
@sk1122 I am assigning this issue to you.

**Comment by sk1122** [comment]
@AJAYSHARMA2012 I have created superuser and logged in local copy of this website but then I was prompted to complete a form.

But how can I directly go to dashboard?

**Comment by garg3133** [comment]
@sk1122 You need to fill that form, after which the application will send those details to the admin (in your case, it will be printed in the terminal) to verify the user. Only after successful verification (by clicking on the link attached with the mail), the user can access the dashboard. This is to ensure that only genuine users are able to access the application.

You can enter any random data in the form and it will work.

**Comment by sk1122** [comment]
@garg3133 So, I should click that link in terminal?

**Comment by garg3133** [comment]
@sk1122 Yes. Then only the application will authenticate the user to use the application.

**Comment by sk1122** [comment]
@garg3133 thanks👍

**Comment by sk1122** [comment]
I have activated the account using the link in the terminal, filled in details, and then redirected to the login page.

But, When I tried to Log In it showed me this error
![Jagrati](https://user-images.githubusercontent.com/40713709/112309944-02038680-8cca-11eb-9e9b-bdb81bfdb378.png)

**Comment by garg3133** [comment]
@sk1122 You must have got another link in the terminal after filling your details. You need to click on that link to verify your profile.

**Comment by sk1122** [comment]
![homework](https://user-images.githubusercontent.com/40713709/112431841-08dfd700-8d66-11eb-9566-b58664f13346.png)

Should it be looking like this

**Comment by garg3133** [comment]
Yep!! @sk1122.
