### ISSUE TITLE
Add subject taught field in CW/HW section

### ISSUE THREAD

**Issue by garg3133** [garg3133/JagratiWebApp#176]
Add a `select` input field in 'Update CW/HW' section on the dashboard for marking which subject was actually taught in the class. This field is already present in the models file, you just need to implement the working of this field.

**Working:**
There will be a `select` input field in 'Update CW/HW' section of the Dashboard, just above the textareas used for submitting the CW-HW. The selected value in the `select` input should be defaulted to the subject scheduled on that day. Whenever a user submits the CW-HW for that day, he/she can also select the subject which was actually taught in the class and then submit the form. On the backend, the selected value will be saved to the database (but only if the CW, HW and comment fields are not all empty).

Also, display the `Subject Taught` alongside the `Subject Scheduled` field on the Dashboard, just below the `Continue` button.

**Comment by archana-1209** [comment]
Hi @garg3133 ,I want  to work  on this  issue.

**Comment by garg3133** [comment]
Sure @archana-1209, go ahead! Assigning you the issue.

**Comment by archana-1209** [comment]
Thanks!

**Comment by garg3133** [comment]
Hey @archana-1209, any progress on this?

**Comment by archana-1209** [comment]
Yes,It is in the progress,will create the PR by tomorrow.Hope this is ok!

**Comment by akshay399** [comment]
hi @garg3133 is anyone working on this issue? or can i try solving it

**Comment by garg3133** [comment]
@akshay399 No, you can take up this issue. Assigning it to you.

**Comment by satwik-talluri** [comment]
Hello!

I am a GSSOC'21 participant.
I would love to work on this feature. I have sound knowledge of Django and Databases and I am confident that I would be able to finish the task promptly.

@garg3133  can you please assign me this issue. Thank you

**Comment by garg3133** [comment]
Sure @satwik-talluri, @akshay399 seems to be busy so you can work on this issue. Assigning it to you.

**Comment by satwik-talluri** [comment]
Thanks for assigning me @garg3133 

I have a small doubt. Can you please point me to the URL that corresponds to the 'Update CW/HW' section in the dashboard?

**Comment by garg3133** [comment]
Just go to dashboard, select any date and section, you'll find a "Update CW/HW" button there.
