### ISSUE TITLE
Create a 404 Page

### ISSUE THREAD

**Issue by garg3133** [garg3133/JagratiWebApp#181]
Create a new 404 Not Found Page. The page should look professional and not too much fancy

**Comment by Sapna2001** [comment]
@garg3133 can I work on  this. I am a gssoc participant.

**Comment by garg3133** [comment]
Sure @Sapna2001, go ahead! Assigning you the issue.

**Comment by simranbhalla3** [comment]
Hi i am a gssoc participant , can i work on this issue?

**Comment by Ayushgup85** [comment]
is this issue still open?
