### ISSUE TITLE
more about us first slide issue

### ISSUE THREAD

**Issue by oneknucklehead** [garg3133/JagratiWebApp#189]
**Describe the bug**
The first slide of the more about page has a photo that is blurry. It should be replaced with another photo or a blank slide which asks the user to either scroll or tap on the go down button on the right side, thus making the page more user friendly.

Can I get assigned to this issue under GSSoC '21?

**Comment by garg3133** [comment]
Actually @oneknucklehead, that page is present on the official website of our institute and so, we don't have the permissions to change anything on that page. We'll try to get the permissions some later time and if we don't get that, we'll be just removing the link to that page from the site.
