### ISSUE TITLE
navbar color code

### ISSUE THREAD

**Issue by oneknucklehead** [garg3133/JagratiWebApp#190]
**Describe the bug**
the navbar hover effect color does not go by the color code of the whole website. When hovered over the navbar, the color should change to black and not red
Can I work on this issue under GSSoC'21?

**Comment by simranbhalla3** [comment]
Hi i am a gssoc participant , can i work on this issue?

**Comment by Naman-12911** [comment]
Hello sir  I want to solve this issue please assign me.under GSSOC.

**Comment by prsndp** [comment]
Hey, I'm gssoc participant and also I have some experience in web dev(django+bootstrap,css) So, please can you assign me this issue?

**Comment by garg3133** [comment]
@oneknucklehead The theme of the website is based on the colours present in the logo of Jagrati. If you see the little dot of `i` in the logo, it is red in colour. The red colour is derived from there.

It's fine with us and we don't want to change that.
