### ISSUE TITLE
[feature]: Form page for adding new event

### ISSUE THREAD

**Issue by Sanjana-03** [garg3133/JagratiWebApp#198]
A new page is required for adding a new event. The page is to be implemented in the `events` app.

**Comment by Sanjana-03** [comment]
I have to startapp for this??

**Comment by garg3133** [comment]
@Sanjana-03 No, I've already created the `events` app. You need to make changes in that.

**Comment by Sanjana-03** [comment]
Okay!

**Comment by garg3133** [comment]
Resolved in #211.
