### ISSUE TITLE
Show all events on a new page

### ISSUE THREAD

**Issue by garg3133** [garg3133/JagratiWebApp#199]
Create a new page in the `events` app to display all the events registered in the application.

You need to show all the events on that page in the form of cards containing event thumbnail, event title and truncated event description.

**Comment by bishakhne0gi** [comment]
I want to work on this issue.

**Comment by garg3133** [comment]
Sure @bishakhne0gi, go ahead! Assigning this issue to you.

**Comment by simranbhalla3** [comment]
I am a Gssoc participant , please assign me this issue.

**Comment by garg3133** [comment]
Any progress on this @bishakhne0gi?

**Comment by bishakhne0gi** [comment]
> Any progress on this @bishakhne0gi?

Yess, I am working on this. Actually, I am out of station and will get my stable network after 2 days.

**Comment by akshay399** [comment]
@garg3133 can i work on this issue?

**Comment by garg3133** [comment]
@akshay399 This issue was opened for @bishakhne0gi because he is completely new to Django. Otherwise, this is not a `Level2` issue.

Can you develop the complete `Events` page for a `Level3` issue? You need to show all the events on that page in the form of cards containing event thumbnail, event title and truncated event description.

**Comment by akshay399** [comment]
yep i can do that, are you going to make a new issue for this? @garg3133

**Comment by garg3133** [comment]
Let me update this issue only.

**Comment by akshay399** [comment]
> Let me update this issue only.

hi @garg3133 i made a [PR](https://github.com/garg3133/JagratiWebApp/pull/252) please review it, thank you

**Comment by garg3133** [comment]
I am currently super busy with my college project and assignment submissions followed by my end-sem exams, so I might not be available for a few days. Sorry for the delay.
