### ISSUE TITLE
Fix Jagrati Tagline

### ISSUE THREAD

**Issue by garg3133** [garg3133/JagratiWebApp#2]
On Jagrati landing page, "an initiative by iiitians" should be replaced with "an initiative of IIITians".

**Comment by Novaenn** [comment]
Shouldn't this issue be closed?

**Comment by garg3133** [comment]
And why is that? This issue has not been fixed yet.

**Comment by adenashameem** [comment]
Please let me know if this issue hasn't been fixed yet.

**Comment by garg3133** [comment]
@adenashameem Yes, this issue is still open. You can take it up.

**Comment by Yashs911** [comment]
@garg3133 If no PR is created till 1st Oct then can I create a PR? I am new to open source and have registered in Hacktoberfest.

**Comment by garg3133** [comment]
Yeah sure, just ask here if someone else is working on the issue (they maybe on the stage of setting up the project). If no one is, you can surely open a PR :)

Also, as you said you are new to Open Source, you may also check out [first-bit](https://github.com/BitByte-TPC/first-bit) where you can practice the complete Git-GitHub workflow before Hacktoberfest and also get featured on the first-bit [website](https://bitbyte-tpc.github.io/first-bit/).😄 But, this is only for you to practice and contribution in this repository (first-bit) won't be counter towards the Hacktoberfest.

**Comment by adenashameem** [comment]
I've opened a PR.

**Comment by garg3133** [comment]
Issue resolved by merging #6. Closing this issue.
