### ISSUE TITLE
Fetch date from Django instead of using Javascript date

### ISSUE THREAD

**Issue by garg3133** [garg3133/JagratiWebApp#20]
**Details on the issue:**
Use dates fetched from Django on `Dashboard`, `Student Attendance` and `Volunteer Attendance` pages. Currently, these pages display dates fetched from JavaScript which in turn uses system date which is a huge security flaw in the application as on changing the system date, the date conceived by app as `today` may be changed. Whereas on fetching date from Django, it will use the server date/time and not system's.

**How to reproduce:**
1. Set up the app on your local pc (instructions given in [README.md](https://github.com/garg3133/JagratiWebApp/blob/master/README.md#contributing).)
2. Create an account in the app (along with completing all profile details).
3. Login with that account.
4. You'll be redirected to `Dashboard`. Here at top-centre, a `Date` field is present which is being fetched from Javascript. You need to fetch it using Django.
5. `Volunteer Attendance` page can be accessed at http://127.0.0.1:8000/volunteers/attendence.
6. `Students' Attendance` page can be accessed at http://127.0.0.1:8000/students/attendence.

Do the same thing done in 4 in 5 and 6 also.

**Note:** This issue can be assigned to 3 people simultaneously who can work on all 3 pages separately and discuss in the community.

For any further doubts and queries, feel free to join the community and ask there: https://discord.gg/Ek9q45ZjAv

**Comment by InfiniteVerma** [comment]
I'll like to work on this.

**Comment by garg3133** [comment]
Sure @InfiniteVerma, go ahead!
Assigning you the issue.

**Comment by garg3133** [comment]
Resoled in #31.
