### ISSUE TITLE
Revamp contact us page

### ISSUE THREAD

**Issue by RahulBansal0502** [garg3133/JagratiWebApp#203]
I want to revamp contact us page. Please assign rhis issue to me @tmo66

**Comment by tmo66** [comment]
@RahulBansal0502 What changes do you propose for the Contact us section?

**Comment by RahulBansal0502** [comment]
![111900672-e85c0800-8a59-11eb-8c93-515d3800be8c](https://user-images.githubusercontent.com/56486309/112660990-0ff90900-8e7c-11eb-9e7c-2851058d0f18.png)
Like this I want to make

**Comment by tmo66** [comment]
Hey @RahulBansal0502, I think the current contact us section looks much better than the one you proposed. 
(I'm closing this issue!)
