### ISSUE TITLE
Contact Us section.

### ISSUE THREAD

**Issue by RubenFalcao14** [garg3133/JagratiWebApp#206]
There is no contact us section in the site . Which makes it difficult for people to contact you'll If they have a query and all.

**Comment by RubenFalcao14** [comment]
I'm a GSSOC'21 participant and I would love to work on it.
Thank You.

**Comment by garg3133** [comment]
Hey @RubenFalcao14, thanks for opening this issue. But we already have a similar issue #165 opened for this and the work for this page is already in progress.

Hence, I'm closing this issue as a duplicate. Hope to see you contribute on other issues currently open :)
