### ISSUE TITLE
Improving the UI donate modal

### ISSUE THREAD

**Issue by cryptofox17** [garg3133/JagratiWebApp#207]
**Is your feature request related to a problem? Please describe.**
This is not a problem however the modal that appears on clicking donate button is very basic and could be improved in terms of the color choices and the alignment and size of the icons used. Even the font weight could be changed.

**Describe the solution you'd like**
Making the modal have a more modern UI using the mentioned changes above.

**Additional context**
I would like to work on this issue.

**Comment by garg3133** [comment]
Hey @cryptofox17, thanks for opening this issue. While we already have a similar issue open, it has been inactive for a long time.

You can surely work on this issue, let me assign it to you.

Please do check the comments on #23 for more info related to this issue.

**Comment by garg3133** [comment]
We'll finalize the final design in 1-2 days and will let you know.

**Comment by cryptofox17** [comment]
@garg3133 ok then
