### ISSUE TITLE
Toggle password field

### ISSUE THREAD

**Issue by niksm7** [garg3133/JagratiWebApp#210]
**Is your feature request related to a problem? Please describe.**
It is quite frustrating to not see the password you are typing during the login and this affects the user experience.

**Describe the solution you'd like**
I would like to add a show password icon/button near to the login input field so that the user can toggle anytime they want.

**Additional context**
I'm a GSSOC '21 participant eager to work on this enhancement and would request you to assign me the same.

**Comment by tushhr** [comment]
Sure @niksm7, go ahead. Assigning you the issue.

**Comment by niksm7** [comment]
Thank you @tushhr. Can you please also add the gssoc'21 label and the level label.
