### ISSUE TITLE
Fixing the About us Section

### ISSUE THREAD

**Issue by tushhr** [garg3133/JagratiWebApp#215]
**Describe the bug**
About us section on the new home page breaks down on the small screen.

**To Reproduce**
1. Go to `\new`
2. Minimize the screen width.
3. Go to the about us section.
4. See the error.

**Expected behavior**
It should "behave" as the about us section of the old home page.

**Comment by tanishq-arya** [comment]
Please assign me this issue under gssoc. 
I cannot view the new home page. Can you help me with it ?

**Comment by garg3133** [comment]
@tanishq-arya Assigned!

For new home page, you can go to http://localhost:8000/new

**Comment by tanishq-arya** [comment]
Hey I can solve the issue. I have already made changes to the css file but I cannot seem to see them in the browser when I refresh again. Can you help me with this ?
![image](https://user-images.githubusercontent.com/77333275/113716766-8dd4d400-9708-11eb-8092-66886cccc80a.png)

**Comment by garg3133** [comment]
Try clearing your browser's cache using `Ctrl + F5` or `Shift + F5`

**Comment by tanishq-arya** [comment]
![Screenshot (1098)_LI](https://user-images.githubusercontent.com/77333275/113719908-bc07e300-970b-11eb-88ae-be7b5ecc0622.jpg)
There is some issue with the container I was thinking of making a new issue for that. Should I do that ?

**Comment by simranbhalla3** [comment]
I am a Gssoc participant , please assign me this issue.

**Comment by garg3133** [comment]
> There is some issue with the container I was thinking of making a new issue for that. Should I do that ?

Yes, I just noticed that. Can you open a new issue for this?
