### ISSUE TITLE
"Integrity Error" on entering already existing roll number

### ISSUE THREAD

**Issue by garg3133** [garg3133/JagratiWebApp#22]
**Details on the issue:**
While completing the profile after a fresh registration on the application, if the roll no. entered in the `Roll No.` field already exists in the database, it displays a yellow screen showing "Integrity Error". Instead, a check must be coded in the application while completing the profile to check if the roll no. entered by the user already exists in the database. If it does, show an error message toast on the page displaying "Roll No. entered already exists.".

**How to reproduce:**
- Set up the app on your local pc (instructions given in [README.md](https://github.com/garg3133/JagratiWebApp/blob/master/README.md#contributing).)
- Create an account in the app (along with completing all profile details).
- Create another account in the app but this time enter the Roll No. used in the previous step.
- You'll see a yellow screen with "Integrity Error" as shown in the screenshot below upon saving.

![image](https://user-images.githubusercontent.com/39924567/101198343-56d2b100-3689-11eb-9d63-0f02577f2a18.png)

Solving this issue will require a basic to intermediate level of knowledge in Django.

For any further doubts and queries, feel free to join the community and ask there: https://discord.gg/Ek9q45ZjAv

**Comment by GunjanDhanuka** [comment]
I am learning Django from just before kwoc started and I think fixing this issue will help me learn further. Please assign this to me and it would be very kind of you if you could point me to any resources I might need. Thanks!

**Comment by garg3133** [comment]
Sure @GunjanDhanuka, you can work on this. Assigning it to you.

For solving this particular issue, you just need to add a check in `complete_profile` view just like I've already added in `update_profile` view. It's just some python code you need to write, you'll understand it while working on it.

Assigning it to you! Feel free to ask here if you're stuck somewhere.

**Comment by garg3133** [comment]
@GunjanDhanuka Are you working on this issue?

**Comment by GunjanDhanuka** [comment]
> 
> 
> @GunjanDhanuka Are you working on this issue?

Yes sir, I was working on the issue but couldn't devote enough time to it to properly solve it. Sorry for that!

**Comment by amanraihot** [comment]
I will be working on it

**Comment by garg3133** [comment]
@GunjanDhanuka If you are working on this issue, that's great! But if you're not, you can un-assign yourself so that someone else can take this.

**Comment by sagarpandyansit** [comment]
I would like to work on this issue. Can you assign it to me? @garg3133

**Comment by garg3133** [comment]
Yeah, sure @sagarpandyansit! Go ahead!

**Comment by garg3133** [comment]
@sagarpandyansit If you have any confusion or face any problem, you may ask here directly. I do not check Slack regularly.

**Comment by sagarpandyansit** [comment]
@garg3133, could you guide me to reproduce this issue as I am unable to reproduce it. The volunteer table itself rejects duplicacy in roll number. and no URL I could find to reproduce it.
https://drive.google.com/file/d/19k0ffnftawbDW8Ye_TYcJRqGfMYONbtN/view?usp=sharing

**Comment by garg3133** [comment]
No, you are approaching it wrongly. A new volunteer won't be added using Admin Portal but he/she is required to create an account in the application for that by going to `http://localhost:8000/accouonts/login`. After successful activation of the email account (by clicking on the link sent through email, is printed on the terminal instead during development), the user will be asked to complete his/her profile.

While completing this profile, if the user enters an already existing `roll_no`, the yellow page shows up displaying "Integrity Error".

**Comment by sagarpandyansit** [comment]
Got it. Thanks.

**Comment by garg3133** [comment]
Resolved in #59.
