### ISSUE TITLE
[bug]: HTML Validation

### ISSUE THREAD

**Issue by tanishq-arya** [garg3133/JagratiWebApp#221]
**Describe the bug**
Sometimes minor issues are missed in html, which might result in SEO issues

**To Reproduce**
https://validator.w3.org/nu/?doc=https%3A%2F%2Fjagrati.herokuapp.com%2F

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by simranbhalla3** [comment]
I am a Gssoc participant , please assign me this issue.

**Comment by garg3133** [comment]
Sure @simranbhalla3, you can work on this. Assigning you the issue!

**Comment by tanishq-arya** [comment]
If no one is working on this. Please assign me this issue.

**Comment by garg3133** [comment]
Sure @tanishq-arya

**Comment by tanishq-arya** [comment]
Yes I am working on the issue and will make a PR soon.

**Comment by tanishq-arya** [comment]
@Jagrati-Bot I am working on this.

**Comment by tanishq-arya** [comment]
@Jagrati-Bot I am working on this issue. Waiting for a review on my PR.
