### ISSUE TITLE
[feature]: Contact Us section modification

### ISSUE THREAD

**Issue by tanishq-arya** [garg3133/JagratiWebApp#222]
**Is your feature request related to a problem? Please describe.**
I think the best way to display the map and contact details is side by side in the desktop view. 

**Describe the solution you'd like**
I would like to change the placement of map in contact us section by making changes to the CSS.

**Describe alternatives you've considered**

**Additional context**
![image](https://user-images.githubusercontent.com/77333275/113752620-cab1c280-972a-11eb-85cf-e4ad34c62638.png)

**Comment by garg3133** [comment]
Can you create a mockup of what you're proposing and send it here so that we get a better idea of how the change will look like before you actually start to work on it?

**Comment by tanishq-arya** [comment]
![image](https://user-images.githubusercontent.com/77333275/114076258-177cd100-98c4-11eb-89c0-1a04461ef851.png)
Something like this. I did this when I was learning SASS. This type of design looks more appealing.

**Comment by garg3133** [comment]
@tanishq-arya I don't feel we need to make any modifications to this section. We might need to improve the style of address, contact number and email, which is being worked on in #226, but other than that, it's mostly fine.

Closing this issue!
