### ISSUE TITLE
[feature]: UI improvement : styling of about us section and navigation bar  

### ISSUE THREAD

**Issue by Suman5501** [garg3133/JagratiWebApp#224]
**Is your feature request related to a problem? Please describe.**
There's a need to style the about us section and navigation bar as the alignment of images and fonts need to be fixed.

**Describe the solution you'd like**
could use material ui or bootstrap for easy implementation.

**Describe alternatives you've considered**
modifying the sections by updating css styles on the components.

**Comment by garg3133** [comment]
Hey @Suman5501, thanks for opening this issue. I assume you must have seen the https://jagrati.herokuapp.com site, which was not updated for a long time (I just updated it). Can you check now if the navbar looks good?

For the about us section, there's already a PR #219 opened, do check that too.

**Comment by garg3133** [comment]
Closing this issue.
