### ISSUE TITLE
[bug]: Fixing Extra space for new home in mobile view

### ISSUE THREAD

**Issue by tanishq-arya** [garg3133/JagratiWebApp#229]
**Describe the bug**
On mobile view the screen has whitespace to the right side and website shrinks down. 

**To Reproduce**

**Expected behavior**

**Screenshots**
![Screenshot (1098)_LI](https://user-images.githubusercontent.com/77333275/114179413-91609900-995c-11eb-88b0-507a0332c32f.jpg)

**Additional context**

**Comment by tanishq-arya** [comment]
Please assign me this issue under gssoc

**Comment by garg3133** [comment]
Sure @tanishq-arya, assigning it to you.

Please also add the screenshot of the bug in the issue description.

**Comment by garg3133** [comment]
Fixed in #225.
