### ISSUE TITLE
Enhance Donations Modal on Home Page

### ISSUE THREAD

**Issue by garg3133** [garg3133/JagratiWebApp#23]
**Details on the issue:**
On clicking the "Donate" button on the top navigation bar, a modal/pop-up appears which has a very basic design and does not look good. It would be better if the design of the modal could be improved (using colours as per the theme of the site).

Below is the screenshot of the modal.

![image](https://user-images.githubusercontent.com/39924567/101200859-e0d04900-368c-11eb-93d4-d37dcf1f3453.png)

Working on this issue requires an intermediate knowledge of HTML and CSS.

For any further doubts and queries, feel free to join the community and ask there: https://discord.gg/Ek9q45ZjAv

**Comment by Aarti002** [comment]
hello sir i'm from 2nd year iiitdmj can i work on this issue?

**Comment by garg3133** [comment]
Sure @Aarti002, go ahead! Assigning you the issue.

**Comment by garg3133** [comment]
@Aarti002 Any progress?

**Comment by Isha77agarwal** [comment]
I want to work on this issue, I have a good knowledge of CSS and HTML.

**Comment by garg3133** [comment]
Yes @Isha77agarwal, you can work on this issue.

**Comment by Isha77agarwal** [comment]
@garg3133 I am having some issues with migration, Can you help?

**Comment by garg3133** [comment]
Yeah sure, what issues are you facing?

**Comment by Isha77agarwal** [comment]
File "C:\Users\isha7\AppData\Local\Programs\Python\Python37\lib\site-packages\decouple.py", line 68, in get
    raise UndefinedValueError('{} not found. Declare it as envvar or define a default value.'.format(option))
decouple.UndefinedValueError: EMAIL_HOST_USER not found. Declare it as envvar or define a default value.

![image](https://user-images.githubusercontent.com/50719265/103154704-2af5a780-47bf-11eb-8a1c-a01d10a0e0dd.png)

**Comment by garg3133** [comment]
Have you created `.env` file in `JagratiWebApp` directory as mentioned in README?

Also, for windows, don't use `source` while activating the environment.

**Comment by Isha77agarwal** [comment]
Yes, I created that file.
I tried without source, it is also not working

**Comment by garg3133** [comment]
Try moving the `.env` file to `JagratiWebApp/Jagrati/settings`.

**Comment by garg3133** [comment]
Also, can you please share the screenshot of your `.env` file?

**Comment by harikishantk** [comment]
I would like to contribute to this issue, May I? I'm SWOC 2021 participant, is this issue comes under SWOC? If so, kindly label this issue under SWOC.

**Comment by garg3133** [comment]
Yeah sure @harikishantk, you can contribute to this. I'll add the label before the coding period starts.

**Comment by Abhir-24** [comment]
Can I work on this issue under SWOC ?

**Comment by garg3133** [comment]
@Abhir-24 For SWOC, @harikishantk asked first so I'll assign the issue to him when SWOC starts. You may look at other issues if any of them interests you.

**Comment by tmo66** [comment]
> File "C:\Users\isha7\AppData\Local\Programs\Python\Python37\lib\site-packages\decouple.py", line 68, in get
> raise UndefinedValueError('{} not found. Declare it as envvar or define a default value.'.format(option))
> decouple.UndefinedValueError: EMAIL_HOST_USER not found. Declare it as envvar or define a default value.

@Isha77agarwal as you are setting up this project in windows, 
use `env\Scripts\activate`, instead of `env/Scripts/activate`.

**Comment by tmo66** [comment]
Hey, @harikishantk are you still working on this?

**Comment by harikishantk** [comment]
> Hey, @harikishantk are you still working on this?

Yes I'm working on it, under GSSoC 21.

**Comment by garg3133** [comment]
@harikishantk Now I'm thinking of removing the second column in the donations modal and keeping two rows instead. The top row should have the bank details (with title and value of each field inline) and in the second column, we can have a small message like this: 

OR  (in the center or as it would look good)
Donate books, clothes, stationery items or anything else which might be useful to the kids. Contact:
...
...
...
for making your donations.

**Comment by garg3133** [comment]
Resolved in #208.
