### ISSUE TITLE
[bug]: Remove <br> tags and add margin using css

### ISSUE THREAD

**Issue by tanishq-arya** [garg3133/JagratiWebApp#231]
**Describe the bug**
The <br> tags are not semantically meant to be used for separation. 
We can do this using CSS by applying padding and margin to the section element.

**To Reproduce**

**Expected behavior**

**Screenshots**
![Screenshot (1169)_LI](https://user-images.githubusercontent.com/77333275/114296203-99891780-9ac7-11eb-9b66-a86af3765472.jpg)
**Additional context**

**Comment by tanishq-arya** [comment]
I would like to work on this under gssoc. Please assign me this issue.

**Comment by tanishq-arya** [comment]
I am working on this waiting for review on the PR.

**Comment by srishtij2000** [comment]
Can I work on this issue?

**Comment by tanishq-arya** [comment]
@srishtij2000 I have already solved the issue and raised a PR for the same. Waiting for the review.

**Comment by tanishq-arya** [comment]
@vinayak3010 Hey. I think the project is not active now. Try contributing somewhere else.

**Comment by vinayak3010** [comment]
ok no problem
