### ISSUE TITLE
[bug]: Donate button in navbar

### ISSUE THREAD

**Issue by tanishq-arya** [garg3133/JagratiWebApp#234]
**Describe the bug**
When we hover over cursor should change to a pointer.

**Comment by tanishq-arya** [comment]
Please assign me this issue under gssoc.

**Comment by garg3133** [comment]
@tanishq-arya It is a very minor bug to be even considered for `level0` label. You can fix this issue in the PR you're currently working on, otherwise, we'll fix it ourselves (instead of going through the long process of issue->PR->PR review->Merge).

Closing this issue.

**Comment by tanishq-arya** [comment]
> @tanishq-arya It is a very minor bug to be even considered for `level0` label. You can fix this issue in the PR you're currently working on, otherwise, we'll fix it ourselves (instead of going through the long process of issue->PR->PR review->Merge).
> 
> Closing this issue.

I was about to ask
