### ISSUE TITLE
Fetch images from events app for the captures page.

### ISSUE THREAD

**Issue by garg3133** [garg3133/JagratiWebApp#238]
For the captures page, the event names and corresponding pictures should be fetched from the `events` app's `gallery` model.

But before that, the `captures` page needs to be shifted to the `events` app, with the endpoint as `events/captures`. This can be done in a separate PR after which the work on the original issue can be resumed.

**Comment by coding-geek21** [comment]
@garg3133 I would like to work on this issue can you please assign me , Thank you !

**Comment by coding-geek21** [comment]
I moved the captures page to events app so should i create a PR for this seperately?

**Comment by garg3133** [comment]
Yes, it would be better if you create a separate PR for this.
