### ISSUE TITLE
Add a table with student schedule on student profile page

### ISSUE THREAD

**Issue by garg3133** [garg3133/JagratiWebApp#239]
Under a new heading of "Schedule", add a table (see tables on dashboard page for reference) with headers `Day`, `Section` and `Subject` and the data underneath (fetch from `StudentSchedule` table, for that student), sorted in order of `Day`.

This is a simple issue and can be done easily with basic knowledge of Bootstrap and Django. The design of the table can be copied from the dashboard page for the most part.

**Comment by satwik-talluri** [comment]
Hello!

I am a GSSOC'21 participant.
I would love to work on this feature. I have sound knowledge of Django and Bootstrap and I am confident that I would be able to finish the task promptly.

@garg3133 can you please assign me this issue. Thank you

**Comment by garg3133** [comment]
Sure @satwik-talluri, go ahead! Assigning you the issue.

Currently, I'm only assigning you this issue but you can start working on other issues too once you open PR for this issue and it's waiting for review.

**Comment by satwik-talluri** [comment]
@Jagrati-Bot Sorry for the delay due to End Sem exams and assignments.
I will finish it before this weekend.

Thank You,
Satwik Talluri
