### ISSUE TITLE
Add a table with volunteer schedule on volunteer profile page

### ISSUE THREAD

**Issue by garg3133** [garg3133/JagratiWebApp#240]
Under a new heading of "Schedule", add a table (see tables on dashboard page for reference) with headers `Day`, `Section` and `Subject` and the data underneath (fetched from `VolunteerSchedule` table, for that volunteer), sorted in order of `Day`.

This is a simple issue and can be done easily with basic knowledge of Bootstrap and Django. The design of the table can be copied from the dashboard page for the most part.

**Comment by satwik-talluri** [comment]
Hello!

I am a GSSOC'21 participant.
I would love to work on this feature. I have sound knowledge of Django and Bootstrap and I am confident that I would be able to finish the task promptly.

@garg3133  can you please assign me this issue. Thank you

**Comment by satwik-talluri** [comment]
Hey @garg3133 

You have initially assigned me a task almost similar to this: https://github.com/garg3133/JagratiWebApp/issues/239. But I got started with this one as I was able to login as volunteer but not student to work on that issue. 

I'm attaching the screenshot of the UI changes that I made. If you can verify that, I will raise a pull request. Also can you please assign me to this task as well?
![Volunteer](https://user-images.githubusercontent.com/56936116/115144530-c8c0fb00-a06a-11eb-8b45-8ede592e7928.png)



Thanks,
Satwik Talluri

**Comment by garg3133** [comment]
@satwik-talluri You need to add the table on the profile page of the volunteer (click on the card containing the volunteer info at the top of the sidebar) and not in the sidebar.

For the student issue, you can visit http://localhost:8000/students/profile/1, it will show you the student profile where you can add the schedule info. You cannot log in as a student to this application as of now.

Sure, assigning you this issue as well.

**Comment by satwik-talluri** [comment]
Hey @garg3133 

Can you verify if this is the change that's expected? If so, can I got ahead with creating the Pull request?

![Volunteer_profile](https://user-images.githubusercontent.com/56936116/115145962-1a20b880-a072-11eb-8dc6-1dd9306c238f.png)


Thanks,
Satwik Talluri

**Comment by garg3133** [comment]
@satwik-talluri Yes, this is pretty much what is expected. But it looks kinda odd. Maybe we can put the "Schedule" title over the card and just out the schedule card just below the profile card. Also, you can reduce the padding around the table as that much space looks a bit odd too.

Once you've done that and it looks fine according to you, you can go ahead and create a PR.

**Comment by satwik-talluri** [comment]
@garg3133 
Can you verify if this is what that's expected? If so, can I got ahead with creating the Pull request?
![Volunteer_final](https://user-images.githubusercontent.com/56936116/115277402-e02edf80-a161-11eb-860e-aec51072aa9a.png)

Thanks,
Satwik Talluri

**Comment by garg3133** [comment]
This looks kinda odd to me. I think the previous design on this page would be better at this point (without much margin/padding around the table, like in the latest picture).

Also, please don't delete your fork after opening a PR, I'm not able to test your changes on my local system.

**Comment by satwik-talluri** [comment]
> This looks kinda odd to me. I think the previous design on this page would be better at this point (without much margin/padding around the table, like in the latest picture).
> 
> Also, please don't delete your fork after opening a PR, I'm not able to test your changes on my local system.

@garg3133  Did you mean the design where the two cards were not merged?
I deleted the fork because it was 1 commit behind.

**Comment by garg3133** [comment]
Just keep it like this only for now and open a PR, I'll have to test these changes myself.
