### ISSUE TITLE
Modifying the "Donate Us" part:

### ISSUE THREAD

**Issue by kirtilodha** [garg3133/JagratiWebApp#245]
We can keep a type of feedback form, in which the donor can provide their contact details if they're interested in donating. After receiving the form, we can contact them from our side and help them in contributing to the organization. This way they just needs to provide their name and phone number and the rest process can be carried out by the organization.

**Comment by garg3133** [comment]
I think all this is not needed. If anyone wants to contribute, they can  directly contact the organization using the contacts provided on the "Donate Us" modal and they'll help them with the contribution.
