### ISSUE TITLE
[feature]: Auto merge PR from dependabot 

### ISSUE THREAD

**Issue by Ankita297** [garg3133/JagratiWebApp#253]
**Is your feature request related to a problem? Please describe.**
github action to Auto merge PR from dependabot  

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**
![done by Ankita297 · Pull Request #5 · Ankita297_Story - Google Chrome 17-04-2021 20_05_45](https://user-images.githubusercontent.com/67833077/115946182-288d2b00-a4dd-11eb-96eb-54cff13f63c5.png)

**Comment by garg3133** [comment]
@Ankita297 I don't think auto-merging the PRs from dependabot is a good idea, as the new releases of the libraries may not be backward compatible. So, I always prefer to read the changelog and make any changes required in the code before merging the PR.
