### ISSUE TITLE
Adding links for emails present in the homepage

### ISSUE THREAD

**Issue by gayatri517** [garg3133/JagratiWebApp#257]
I want to add the links to the email ids present in the "home page" and the "donate" section so that the user is more comfortable in contacting. I would also like to add a small icon of a phone in the "donate" section, beside the numbers specified.
Please assign me this issue. @garg3133

**Comment by garg3133** [comment]
Hey @gayatri517, sorry for the delay. Are you still interested in working on this issue?

**Comment by gayatri517** [comment]
@garg3133 Yes

**Comment by garg3133** [comment]
Great, assigning it to you.
