### ISSUE TITLE
Disable Continue button on Dashboard until AJAX is fully loaded

### ISSUE THREAD

**Issue by garg3133** [garg3133/JagratiWebApp#26]
On changing the `Date` on the main dashboard (after logging in), `Section` is fetched from the database for that particular date using AJAX. But sometimes, AJAX can get slow which can lead to delay in the fetching of `Section` on changing the `Date`. If the user clicks the `Continue` button at this time, wrong combination of `Date` and `Section` is sent back to the backend.

To avoid this, we should disable the `Continue` button until the AJAX is fully loaded.

Solving this issue requires basic to intermediate knowledge of HTML, CSS and Javascript.

For any further doubts and queries, feel free to join the community and ask there: https://discord.gg/Ek9q45ZjAv

**Comment by tejaswari7** [comment]
Hi can I work on this issue?
I m a beginner to opensource

**Comment by garg3133** [comment]
Yes sure @tejaswari7, you can work on this.
Assigning you the issue!

**Comment by garg3133** [comment]
Resolved in #33.
