### ISSUE TITLE
[feature]: Form for creating/updating of a student

### ISSUE THREAD

**Issue by harshakhmk** [garg3133/JagratiWebApp#263]
- We can have a form for adding new student details and updating existing student details in ```apps/students``` folder

- I would like to implement the request payload through Django forms instead of hard-coding them.
- Through forms, we can have better error handling 

I would like to work on this @garg3133

**Comment by garg3133** [comment]
Yes, I agree with you that using django forms would be better. Surely you can work on this. Assigning it to you.

**Comment by harshakhmk** [comment]
Shall I also change HTML forms with Django forms when a GET request is made

**Comment by garg3133** [comment]
@harshakhmk Yes, you can, but just make sure that it does not affect the page structure and design.

**Comment by harshakhmk** [comment]
I handled POST data using forms, shall I be raising separate MR for updating HTML code with Django forms or should I be rasing in the same MR with a different commit

**Comment by garg3133** [comment]
You can do that in the same PR.

**Comment by harshakhmk** [comment]
@garg3133  I have raised the PR [274](https://github.com/garg3133/JagratiWebApp/pull/274)
