### ISSUE TITLE
Forget password improvement

### ISSUE THREAD

**Issue by kumarishalini6** [garg3133/JagratiWebApp#264]
**Is your feature request related to a problem? Please describe.**
I want to add border and shadow to give that page beautiful 
![Jagrati _ Password Reset - Personal - Microsoft​ Edge 5_16_2021 10_11_15 AM](https://user-images.githubusercontent.com/69043944/118385726-08252d80-b5be-11eb-877c-236721fbb7ab.png)

**Comment by kumarishalini6** [comment]
please assign this issue to me.

**Comment by garg3133** [comment]
Sure @kumarishalini6, you can try this out, and if it looks good, I'll surely merge the PR.

**Comment by kumarishalini6** [comment]
Please add level on this issue

**Comment by garg3133** [comment]
I'll add the label once your PR is merged, don't worry about that.

**Comment by kumarishalini6** [comment]
Ok
