### ISSUE TITLE
[feature]: Preloader

### ISSUE THREAD

**Issue by kumarishalini6** [garg3133/JagratiWebApp#269]
**Is your feature request related to a problem? Please describe.**
I have seen there is no Preloader in this project i want to work on this issue user GSSoC;21.

**Comment by garg3133** [comment]
I don't feel the need for a preloader in this project. It kind of feels frustrating to me having to keep watching the preloader before the page loads completely (without the preloader, at least we can read the text until the images are loaded completely).
