### ISSUE TITLE
[feature]: Scroll top button on capture page

### ISSUE THREAD

**Issue by kumarishalini6** [garg3133/JagratiWebApp#270]
**Is your feature request related to a problem? Please describe.**
I want to add scroll button in capture page . Can I work on this issue under GSSoC'21 participant.

**Comment by garg3133** [comment]
@kumarishalini6 There is currently no event page. Which page are you referring to?

**Comment by kumarishalini6** [comment]
sorry it should be capture pages.

**Comment by garg3133** [comment]
Ohk sure, you can work on that. Assigning it to you.
