### ISSUE TITLE
New Page: List of all Volunteers

### ISSUE THREAD

**Issue by garg3133** [garg3133/JagratiWebApp#28]
We need a new page to be displayed at `/volunteers/` to list all the volunteers currently a part of the initiative, in the form of clickable cards which will take us to the volunteer profile upon click.

Working on this issue will require knowledge of HTML, CSS + Bootstrap4 and a basic knowledge of Django.

For any further doubts and queries, feel free to join the community and ask there: https://discord.gg/Ek9q45ZjAv

**Comment by jkrlr** [comment]
I want to work on that, can I?

**Comment by garg3133** [comment]
Sure @jkrlr, go ahead!
Assigning you the issue.

**Comment by jkrlr** [comment]
Thank you @garg3133 !!!

**Comment by prakhar1144** [comment]
Hey @jkrlr  are you working on this issue ? If  not please let me know.

**Comment by jkrlr** [comment]
hey @prakhar1144 I am working on it.

**Comment by nporia** [comment]
i would like to work on it too.

**Comment by tmo66** [comment]
Hey, @jkrlr are you still working on this?

**Comment by subhangi2731** [comment]
please assign me this too

**Comment by SmritiAgrawal04** [comment]
Is this issue closed or open yet. If open, can I work on the same?

**Comment by garg3133** [comment]
This is implemented now.
