### ISSUE TITLE
[bug]: Making transitions in Our Initiatives section smoother and equal timed

### ISSUE THREAD

**Issue by sparshsharma2510** [garg3133/JagratiWebApp#281]
**Describe the bug**
I want to smoothen the transition while hovering over the cards in the Our Initiatives section to make them well-timed so that the header and the info card appear simultaneously.
**To Reproduce**
1. Go to 'the landing page'
3. Scroll down to 'Our Initiatives section'
4. See error 'On hovering the info card appears before then the header arrives at the top'

**Expected behavior**
When hovering over the card the info card and the header should appear at the same time.
**Screenshots**

**Additional context**

**Comment by garg3133** [comment]
Sure @sparshsharma2510, go ahead! Assigning you the issue.
