### ISSUE TITLE
Automate Copyright year updation according to current year

### ISSUE THREAD

**Issue by garg3133** [garg3133/JagratiWebApp#3]
Find all the places where Copyright message is written and automate Copyright year updation by replacing year written manually with `{% now 'Y'%}` template tag.

Also, do share screenshot in the PR showing that it is working properly.

**Comment by ion05** [comment]
Can i work on this ?

**Comment by garg3133** [comment]
@ion05 Yeah sure, go ahead!

**Comment by ChiragSharma1** [comment]
@ion05  are you still working on it ?

**Comment by ChiragSharma1** [comment]
@garg3133 , He isn't replying so can i start working on it Or should wait for his reply.

**Comment by ChiragSharma1** [comment]
@garg3133 , he isn't replying ,so can i start working on it Or have to wait for his reply?

**Comment by garg3133** [comment]
Yeah sure, you can take this up.
