### ISSUE TITLE
Resend Activation Mail

### ISSUE THREAD

**Issue by garg3133** [garg3133/JagratiWebApp#34]
Whenever a new user signs up, we send an activation link to his/her email address order to verify the same. But sometimes it may happen that the user may forget to verify his/her email address and the activation link may get expired. If this happens, the user will be permanently locked out of the app and won't be able to register again with the same email unless he/she contacts the admin.

So, there must an option to resend the activation link to the registered email address. The option should be available in the error message which appears while trying to log in with an unverified email address. You can use the existing `account_activation_token` in `accounts/tokens.py` to resend the activation email.

Working on this issue requires an intermediate knowledge of Django.

For any further doubts and queries, feel free to join the community and ask there: https://discord.gg/Ek9q45ZjAv

**Comment by InfiniteVerma** [comment]
I'll like to work on this.

**Comment by garg3133** [comment]
Sure @InfiniteVerma, assigning you the issue!

**Comment by N00Bmaster2810** [comment]
Hi @garg3133 sir if this issue is still open, can I try working on this

**Comment by tmo66** [comment]
Sure @N00Bmaster2810, you can work on this issue if @InfiniteVerma  is not.

@InfiniteVerma Can you please respond if you are working on this or not?

**Comment by Haneesha123** [comment]
I would like to work on this issue @garg3133

**Comment by garg3133** [comment]
Sure @Haneesha123, go ahead! Assigning you the issue.

**Comment by Haneesha123** [comment]
@garg3133 I am having a problem sending verification mail. I have put the right credentials as you mentioned in the .env file. But still, I am getting an SMTP authentication error. Can you help me out?
![image](https://user-images.githubusercontent.com/61455329/111179163-ceda3c80-85d1-11eb-8c7b-ea5eee6547ca.png)

**Comment by garg3133** [comment]
@Haneesha123 Your `SENDER_EMAIL` is wrong. It should be `Jagrati <orionwebsite123@gmail.com>`

**Comment by Haneesha123** [comment]
Yeah got it, Thank you!

**Comment by garg3133** [comment]
@Haneesha123 What is the progress on this?

**Comment by Haneesha123** [comment]
@garg3133 I am trying. Can you give me one more day?

**Comment by garg3133** [comment]
Yeah sure, no problem!
