### ISSUE TITLE
Add gender field in Student model

### ISSUE THREAD

**Issue by garg3133** [garg3133/JagratiWebApp#35]
Add a `gender` field in `Student` model of students app. You may refer to the `Profile` model present in the accounts app.

Working on this issue requires **basic** knowledge of Django.

For any further doubts and queries, feel free to join the community and ask there: https://discord.gg/Ek9q45ZjAv

**Comment by nayaldivya** [comment]
I want to work on this issue. Can you please assign me this.

**Comment by garg3133** [comment]
Sure @nayaldivya!

**Comment by garg3133** [comment]
Resolved in #51.
