### ISSUE TITLE
Add DP for students

### ISSUE THREAD

**Issue by garg3133** [garg3133/JagratiWebApp#36]
Add a `display_picture` in `Student` model. Also, you need to use `imagekit` to compress the image before storing it.

You may refer to the implementation of profile picture for user profile in `Profile` model of accounts app.

Working on this issue requires **intermediate** knowledge of Django.

For any further doubts and queries, feel free to join the community and ask there: https://discord.gg/Ek9q45ZjAv

**Comment by TrushaT** [comment]
I would like to work on this issue.Pls assign it to me

**Comment by garg3133** [comment]
Sure thing @TrushaT!

**Comment by pawankm21** [comment]
I would like to work on this issue, I have done this before in my dummy project.

**Comment by garg3133** [comment]
Hey @TrushaT, are you still working on this issue?

**Comment by TrushaT** [comment]
Yes. I will create a PR by tomorrow .

**Comment by garg3133** [comment]
Resolved in 99bdae8.
