### ISSUE TITLE
CODE OF CONDUCT and CONTRIBUTION file 

### ISSUE THREAD

**Issue by akrish4** [garg3133/JagratiWebApp#37]
Hi @garg3133 
This is a great intiative 
I would like to contribute to this project , I found that there is no code_of_conduct file and you know code of conduct is an important file which all the contributors need to follow so I would like to work on this issue , I can make a new file of code of conduct and a contribution file and can copy the contribution guidelines given in README file and can improve README file
Kimdly assigne me

**Comment by garg3133** [comment]
Thank you @akrish4 for the suggestion. This sounds great!
Assigning this issue to you.

**Comment by akrish4** [comment]
> Thank you @akrish4 for the suggestion. This sounds great!
> Assigning this issue to you.

Thank you @garg3133 
Since this project is registered under SWOC , kinldy add the `SWOC2021` , `SWOC` and `medium`tags to issue

**Comment by akrish4** [comment]
@garg3133  I was the first person to open a issue regarding code of conduct and contributing , Let him work on issue template

**Comment by akrish4** [comment]
I have worked on it and made the pr 
#49 PR

**Comment by garg3133** [comment]
Resolved in #49.
