### ISSUE TITLE
Replace `Change Password` with `Dashboard` on header

### ISSUE THREAD

**Issue by garg3133** [garg3133/JagratiWebApp#38]
Replace `Change Password` to `Dashboard` on the header. The header will be visible only after logging into the application.

**Comment by Utkarsh-Agarwal-585** [comment]
I'm ready to work on this...Can you please provide some extra info about where I'll get this file?

**Comment by garg3133** [comment]
You can find the `header.html` file in `templates/snippets` folder.

**Comment by pritamp17** [comment]
@garg3133 sir I would like to work on this issue,  could please assign this to me in incase nobody is working on this?

**Comment by garg3133** [comment]
@Utkarsh-Agarwal-585 Are you working on this issue?

**Comment by Utkarsh-Agarwal-585** [comment]
Yes, I'm working

**Comment by garg3133** [comment]
@Utkarsh-Agarwal-585 It is a very straight-forward issue. If you are not working on this, please unassign yourself from the issue.

**Comment by Utkarsh-Agarwal-585** [comment]
> @Utkarsh-Agarwal-585 It is a very straight-forward issue. If you are not working on this, please unassign yourself from the issue.

I'm working on it

**Comment by SwarupKharul** [comment]
Can u please assign me the task, I know what is to be done exactly. I am a participant of MWoC.

**Comment by garg3133** [comment]
Sure @SwarupKharul, you can take this issue.

@Utkarsh-Agarwal-585 It's been 35 days since you took up this issue. So, I'm unassigning you from this issue.

**Comment by garg3133** [comment]
Resolved in #96, thanks @SwarupKharul!
