### ISSUE TITLE
Updating Home Page

### ISSUE THREAD

**Issue by tmo66** [garg3133/JagratiWebApp#39]
The current Home page looks dull, can I shift it to `/old` with new Index Page on `/` .

**Comment by RutvikJ77** [comment]
Hey is this issue still open? 
I see there are pull requests made but in case if it's open I would like to work on it.

**Comment by Riya764** [comment]
I would like to work on this issue.Please /assign this to me as a part of GSSOC'21

**Comment by garg3133** [comment]
@Riya764 This issue needs some further discussion with the team so we are currently not taking contributions on this issue. You can take a look at other issues if any interests you. Thank you.

(I am locking this issue.)
