### ISSUE TITLE
[Docs]: Add Issue Template, Pull Request template, Code Of Conduct 

### ISSUE THREAD

**Issue by deytulsi18** [garg3133/JagratiWebApp#40]
Can I add Issue Template, Pull Request template, Code Of Conduct suitable for this project?

**Comment by garg3133** [comment]
Yes @deytulsi18, that'll be a good idea. Making code of conduct will be addressed in #37, you can work on other two files.

**Comment by Sloth-Panda** [comment]
Hey, can I proceed with the above mentioned  issue?

**Comment by garg3133** [comment]
Fixed in a2f3d33.
