### ISSUE TITLE
Create a personal-info card on sidebar

### ISSUE THREAD

**Issue by garg3133** [garg3133/JagratiWebApp#41]
Convert the marked portion of the sidebar in the image below to a **clickable card** which upon click (anywhere on the card) will take the user to the profile page (`/volunteers/profile/<user_id>/`).
![image](https://user-images.githubusercontent.com/39924567/103486797-78f55580-4e26-11eb-9fce-c73b3088e0f8.png)

Also, the card should contain profile picture, name and designation of the user (show `Volunteer` as designation if `desig` field in `Volunteer` model is set to `null`). All these three things should be centre-aligned without any heading.

Working on this issue requires **basic/intermediate** knowledge of Bootstrap 4 and **basic knowledge** of Django.

For any further doubts and queries, feel free to join the community and ask there: https://discord.gg/Ek9q45ZjAv

**Comment by sakshikhachane** [comment]
@garg3133 I would like to work on this issue. Please assign me this issue.

**Comment by garg3133** [comment]
Great @sakshikhachane, assigning you the issue!

**Comment by m-code12** [comment]
@garg3133 I would like to take up this issue.

**Comment by garg3133** [comment]
Sure @m-code12, go ahead! Assigning it to you.
