### ISSUE TITLE
Modify AJAX calls to use POST method

### ISSUE THREAD

**Issue by garg3133** [garg3133/JagratiWebApp#42]
Modify all AJAX calls in `volunteers` and `students` app to use POST method instead of GET.

Working on this issue requires intermediate knowledge of JavaScript.

For any further doubts and queries, feel free to join the community and ask there: https://discord.gg/Ek9q45ZjAv

**Comment by tabishnehal** [comment]
Hi @garg3133 ...I would like to work on it...can you assign it to me?

**Comment by garg3133** [comment]
Sure @tabishnehal, go ahead!

**Comment by sammy8825** [comment]
I would like to work on this issue @garg3133 can u assign it to me?

**Comment by garg3133** [comment]
@tabishnehal Are you working on it?

**Comment by tabishnehal** [comment]
@garg3133 ohk you may assign to @sammy8825 .. I have not done significant work due to busy schedule so yeah you can assign to @sammy8825

**Comment by nehaparmar99** [comment]
Can I work on this issue @garg3133 ?

**Comment by garg3133** [comment]
Hey @nehaparmar99, I think @sammy8825 is currently working on this issue.

**Comment by sammy8825** [comment]
Yes, @garg3133 I'm working on it. please give me some more time

**Comment by garg3133** [comment]
Sure @sammy8825!

**Comment by garg3133** [comment]
Resolved in #63.
