### ISSUE TITLE
Replace `Back to Dashboard` to `Refresh Page`

### ISSUE THREAD

**Issue by garg3133** [garg3133/JagratiWebApp#43]
Replace `Back to Dashboard` link at the top-left of each page with `Refresh Page` on all the page it is appearing in.

Also, don't forget to include the "reload" icon before `Refresh Page`, just like on Dashboard.

Working on this issue requires basic knowledge of HTML.

For any further doubts and queries, feel free to join the community and ask there: https://discord.gg/Ek9q45ZjAv

**Comment by N00Bmaster2810** [comment]
Sir, can I work on this under SWOC

**Comment by garg3133** [comment]
Sure @N00Bmaster2810, you can work on this.

**Comment by garg3133** [comment]
Resolved in #44.
