### ISSUE TITLE
New Page: Add a new student

### ISSUE THREAD

**Issue by garg3133** [garg3133/JagratiWebApp#47]
We need a new page to add new students in the `Student` model. The page will be displayed at `/students/new/` and will have all the fields as in the `Student` model.

You may refer to `complete_profile` page which appears after signing up into the application.

Working on this issue will require knowledge of HTML, CSS + Bootstrap4 and a basic knowledge of Django.

For any further doubts and queries, feel free to join the community and ask there: https://discord.gg/Ek9q45ZjAv

**Comment by Aniket118** [comment]
I would like to work on this issue.

**Comment by amanraihot** [comment]
I am working on it

**Comment by Aniket118** [comment]
Can you please put this under swoc lable ?

**Comment by garg3133** [comment]
Yes @Aniket118, sure!

**Comment by N00Bmaster2810** [comment]
Hey @garg3133 ,If this issue is unassigned could you please assign it to me?

**Comment by garg3133** [comment]
I think @Aniket118 is not working on this issue.
@N00Bmaster2810 You can take this issue. Assigning it to you!

**Comment by N00Bmaster2810** [comment]
Thanks @garg3133

**Comment by garg3133** [comment]
Resolved in #61.
