### ISSUE TITLE
Improve text in Donation section on landing page

### ISSUE THREAD

**Issue by garg3133** [garg3133/JagratiWebApp#5]
Donation section on landing page currently contains `lorem ipsum` text. Write something else in place of that.

**Comment by ankitsridhar16** [comment]
I would like to fix it

**Comment by adenashameem** [comment]
I can take this up.

**Comment by garg3133** [comment]
@ankitsridhar16 Sure, you can work on this issue.

@adenashameem You can work on #2 for now. I'll be soon opening more such issues.

**Comment by sakshi006** [comment]
Hey!
i would like to work on this issue.

**Comment by Mahikta** [comment]
Can I work on the same as well?

**Comment by garg3133** [comment]
@sakshi006 You can work on this.

**Comment by rohan8660** [comment]
Can I work on this ?

**Comment by garg3133** [comment]
@sakshi006 @Mahikta Anyone of you interested in working on this issue? If yes, you can claim this issue by commenting here and start working on it.

@rohan8660 Just wait for around 6 hours. If no one of them claims this issue by that time, you can claim this issue and start working on it.

**Comment by rohan8660** [comment]
@garg3133 OKAY

**Comment by rohan8660** [comment]
@garg3133  It has been seven hours since, I will start working on it now.

**Comment by rohan8660** [comment]
How many words should I fill in Donation Section?

**Comment by rohan8660** [comment]
Please check the new PR #8, and suggest changes if any.

**Comment by hambali999** [comment]
Hi! Can i work on this? This is my first time pulling a request

**Comment by hambali999** [comment]
assign to me

**Comment by garg3133** [comment]
Resolved in #19.
