### ISSUE TITLE
contact icon

### ISSUE THREAD

**Issue by palak199** [garg3133/JagratiWebApp#52]
![image](https://user-images.githubusercontent.com/43077980/104048702-b46a9800-5209-11eb-8752-862f8aa0c5e1.png)
here the red contact us label opens on hover.
but a newbie can miss it out since only **con** appears. I think it can be replaced with a font awesome icon of phone.
I would like to do that if its needed.

**Comment by garg3133** [comment]
That would be great @palak199! You can work on this.
Assigning it to you :rocket:

**Comment by garg3133** [comment]
Resolved in #71.
