### ISSUE TITLE
A profile page for students

### ISSUE THREAD

**Issue by palak199** [garg3133/JagratiWebApp#54]
Currently there isn't an option for students to view their profile. 
- [x] I would like to add the student profile page. Please assign it to me.

**Comment by garg3133** [comment]
That's great @palak199, go ahead!
Assigning it to you.

**Comment by palak199** [comment]
I have added the page in issue #53   commits

**Comment by garg3133** [comment]
@palak199 Please keep work related to different issues in different PR. I missed this while reviewing your PR but you should never create a PR from `master` branch. Always create a new branch before starting to work on any issue.

**What you can do now?**
* Create a new branch from master (`git checkout -b branch-name`) for the contact-icon issue and then reset the commits for the Student Profile page from that branch (`git reset --hard <last-commit-id-of-con-icon-issue>`) and then create a PR.
* Checkout to `master` and create an another branch for this issue and then rebase it to drop the commits related to con-icon issue. You may refer to this doc from Zulip: https://zulip.readthedocs.io/en/latest/git/fixing-commits.html#deleting-old-commits.

**Comment by garg3133** [comment]
Resolved in #72.
