### ISSUE TITLE
Intergrate Welcome Bot 

### ISSUE THREAD

**Issue by akrish4** [garg3133/JagratiWebApp#56]
Hi @garg3133 
I can make  a welcome and greeting bot which will welcome all users who opens a issue and pull request for the first time 
using a config.yml file 
Kindly do assign me 

For reference, check out: https://github.com/apps/welcome

If you feel this is a great idea!
Please assign it to me.

**Comment by garg3133** [comment]
That'll be great @akrish4!
Just see to it that the welcome message looks professional.

**Comment by akrish4** [comment]
> That'll be great @akrish4!
> Just see to it that the welcome message looks professional.

Yes sure

**Comment by Aayush-hub** [comment]
@akrish4 Hey, are you still working on it or I can take over it?

**Comment by akrish4** [comment]
> @akrish4 Hey, are you still working on it or I can take over it?

Yes go ahead @Aayush-hub 
I am bit busy
