### ISSUE TITLE
[TEST] Email field is not properly checking the regular expression for email

### ISSUE THREAD

**Issue by sagarpandyansit** [garg3133/JagratiWebApp#57]
**Details on the issue:**
While signing up for the volunteer or faculty, if you fill email-id randomly, it won't show any error.

**How to reproduce:**
Go to `localhost:8000/accounts/login/` link. Try to enter "admin@gma" and password. It won't show any error and try to send an activation link.

**How to solve it:**
Make a JavaScript function that can check the regular expression for email.

**Comment by garg3133** [comment]
Great job catching this issue @sagarpandyansit! I never noticed this.

**Comment by raman08** [comment]
I would like to work on this issue

**Comment by garg3133** [comment]
Sure @raman08, go ahead! Also, before going into writing a JavaScript function, do check if this issue can be resolved from HTML only. You may refer to MDN docs.

**Comment by raman08** [comment]
Okk sir

**Comment by garg3133** [comment]
Resolved in #69.
