### ISSUE TITLE
[FEATURE] Strong password recommended

### ISSUE THREAD

**Issue by sagarpandyansit** [garg3133/JagratiWebApp#58]
**Details on the issue:**
While signing up for the volunteer or faculty, if you fill in anything except null as a password, it will be accepted. Password should be strong that contains at least 1 special character, at least 1 character should be in uppercase, at least 1 number should be there.
 
**How to reproduce:**
Go to `localhost:8000/accounts/login/` link. Try to enter 'a' as a password. It won't show any error.
 
**How to solve it:**
Make a JavaScript function that can check the regular expression for a strong password. If a password is not strong, give the error accordingly.

**Comment by sagarpandyansit** [comment]
I would like to work on this as well. Kindly assign it to me.

**Comment by garg3133** [comment]
@sagarpandyansit Django itself has a pretty good strong password checking system in place. You should use that for resolving this issue.

**Comment by sagarpandyansit** [comment]
Okay. I will check.

**Comment by sagarpandyansit** [comment]
@garg3133, I spent almost a day finding the working of Django built-in Password validators. I found that it's applicable with forms.py only. It can't inherit to HTML file. Please verify once again if you think that it works in our case too and let me know.

**Comment by sagarpandyansit** [comment]
@garg3133, you can assign this issue to someone else. I am currently working on the other issue.

**Comment by anikashc** [comment]
Please assign this issue to me.

**Comment by garg3133** [comment]
Sure @anikashc, go ahead! Assigning it to you.

**Comment by RituCs** [comment]
Hello, I want to work on this issue. If it is still open please assign me.

**Comment by garg3133** [comment]
Sure @RituCs, you can take this issue.

**Comment by ANAMIKA1410** [comment]
Hey, I am Anamika, a GSSOC'21 Participant.
I would like to contribute to this issue.
aim: strong password code in python

please assigne this to me.

**Comment by garg3133** [comment]
Sure @ANAMIKA1410, as @RituCs has not shown any progress until now, I'm assigning this issue to you.

**Comment by ANAMIKA1410** [comment]
<!DOCTYPE html> 
<html> 
<head>     
       <title>validate password</title>     
       <script type="text/javascript">         
              function test_str() {             
                      var res;            
                      var str =                 
                           document.getElementById("t1").value;            
                      if (str.match(/[a-z]/g) && str.match(                    
                                     /[A-Z]/g) && str.match(                     
                                    /[0-9]/g) && str.match(                     
                                    /[^a-zA-Z\d]/g) && str.length >= 8)               
                              res = "TRUE";            
                      else                 
                              res = "FALSE";             
                      document.getElementById("t2").value = res;          
             }    
      </script> 
</head>  
 <body>     
        <p>        
                String:        
               <input type="text"       
                         placeholder="abc"
                          id="t1" />         
              <br/>        
              <br/>        
             <input type="button"      
                          value="Check"     
                          onclick="test_str()" /> 
             <br/>        
             <br/> Output:    
            <input type="text"      
                         id="t2"        
                        readonly/> 
        </p> 
</body> 
</html>
--

**Comment by Naman-12911** [comment]
I want to work on this issue please assign me under GSSOC

**Comment by ANAMIKA1410** [comment]
import re 
password = input()
flag = 0
while True:   
    if (len(password)<8): 
        flag = -1
        break
    elif not re.search("[a-z]", password): 
        flag = -1
        break
    elif not re.search("[A-Z]", password): 
        flag = -1
        break
    elif not re.search("[0-9]", password): 
        flag = -1
        break
    elif not re.search("[_@$]", password): 
        flag = -1
        break
    elif re.search("\s", password): 
        flag = -1
        break
    else: 
        flag = 0
        print("Valid Password") 
        break
  
if flag ==-1: 
    print("Not a Valid Password")

**Comment by garg3133** [comment]
No @ANAMIKA1410, you don't need to write anything of this sort for this issue but use the Django's already existing password validators.

**Comment by Ananya9878** [comment]
Please assign this issue to me.

**Comment by garg3133** [comment]
@ANAMIKA1410 Are you able to work on this?
(This issue requires good familiarity with Django)

**Comment by Ananya9878** [comment]
@garg3133 I can work on that

**Comment by garg3133** [comment]
@Ananya9878, let's wait for @ANAMIKA1410 response. If she does not respond by the evening, you can start working on this issue.

**Comment by Ananya9878** [comment]
@garg3133 Yes I'll start working after it gets assigned to me.

**Comment by ANAMIKA1410** [comment]
from django import forms
from django.contrib import auth

class ValidatingPasswordChangeForm(auth.forms.PasswordChangeForm):
    MIN_LENGTH = 8

    def clean_new_password1(self):
        password1 = self.cleaned_data.get('new_password1')

        # At least MIN_LENGTH long
        if len(password1) < self.MIN_LENGTH:
            raise forms.ValidationError("The new password must be at least %d characters long." % self.MIN_LENGTH)

        # At least one letter and one non-letter
        first_isalpha = password1[0].isalpha()
        if all(c.isalpha() == first_isalpha for c in password1):
            raise forms.ValidationError("The new password must contain at least one letter and at least one digit or" \
                                        " punctuation character.")

        # ... any other validation you want ...

        return password1

**Comment by ANAMIKA1410** [comment]
@garg3133 mam please check it once.

**Comment by garg3133** [comment]
@ANAMIKA1410 First of all, I'm not a girl :)

About your code, it seems right but we don't need to write our own password validators as Django already provides them out-of-the-box. You just need to use the `validate_password` function which you can import from `django.contrib.auth.password_validation` inside the views and use it. See: https://docs.djangoproject.com/en/3.0/topics/auth/passwords/#module-django.contrib.auth.password_validation

Also, don't create any forms. Use the password validator inside the `login_signup` view only. I leave the implementation details to you.

**Comment by Ananya9878** [comment]
Pls assign this issue to me.

**Comment by garg3133** [comment]
Sure @Ananya9878, you can work on this now as this PR has been inactive for a long time now.

**Comment by Ananya9878** [comment]
> Hello @Ananya9878, you claimed this issue to work on it, but this issue and any referenced pull requests haven't been updated for 10 days. Are you still working on this issue?
> 
> If so, please update this issue by leaving a comment on this issue to let me know that you're still working on it. Otherwise, I'll automatically remove you from this issue in 4 days.
> 
> If you've decided to work on something else, simply unassign yourself from this issue by going to the `Assignees` section and clicking on `unassign me`, so that someone else can claim it and continue from where you left off.
> 
> Thank you for your valuable contributions to JagratiWebApp!

I'm working on it ......will update it soon

**Comment by Ananya9878** [comment]
@garg3133 Can you please review it once
