### ISSUE TITLE
[TEST] Contact No. Field is not restricting user to input only 10 digit numbers.

### ISSUE THREAD

**Issue by nayaldivya** [garg3133/JagratiWebApp#60]
**Details on Issue**: After signing up, while filling the details in Complete your Profile section, Contact no. field is not showing any error if user inputs a number greater than 10 in length, or if the first digit of the number is 0.

![IMG_20210112_010642](https://user-images.githubusercontent.com/73695161/104229614-8340d080-5472-11eb-8cf7-f648b50634fd.jpg)

**Comment by nayaldivya** [comment]
I would love to work on this issue. Please assign this to me.

**Comment by garg3133** [comment]
Hey @nayaldivya, thanks for raising the issue. But I do remember that I imposed this check on the Contact No. but maybe I've not deployed on Heroku yet. This seems to work fine on the development environment.

**Comment by nayaldivya** [comment]
Okay.
