### ISSUE TITLE
Setup permissions to access "Add new student" page

### ISSUE THREAD

**Issue by N00Bmaster2810** [garg3133/JagratiWebApp#65]
Since we have a page to add students, it will be good to have a group called as a "student manager" which comprise of some students or volunteers who will have authentication rights to add a new student.

**Comment by garg3133** [comment]
Yeah, we'll have a `Group` named `Student Manager` and that group must be assigned the permission to add new students.

Only the users who have permission to add new students must be able to open "Add new student" page. (Everyone having "Student Manager" group will automatically have that permission.

**Comment by garg3133** [comment]
Resolved in 59bae57.
