### ISSUE TITLE
Different pictures for initiative cards on home page

### ISSUE THREAD

**Issue by Aiswarika** [garg3133/JagratiWebApp#70]
The "Our Initiative" section on the home page has 9 cards having the same picture. I think it would look better if we replace them with different pictures for each card. I would like to work on this issue if needed.
![Screenshot (212)](https://user-images.githubusercontent.com/72227445/105019494-26de4200-5a6c-11eb-9f6f-ad969d80af63.png)

**Comment by garg3133** [comment]
Thanks @Aiswarika for opening this issue. But, we are currently working on fetching all the contents of initiatives from the database itself in issue #14. So, making any changes in HTML now would just be a waste of effort.

Closing this issue.
