### ISSUE TITLE
Write unit tests for login_signup view

### ISSUE THREAD

**Issue by garg3133** [garg3133/JagratiWebApp#76]
Write unit tests for `login_signup` view in the `accounts` app. The tests need to be added in a file `test_views` in `test` directory of `accounts` app.

To learn about how to write unit tests in Django, you may follow this tutorial from MDN: https://developer.mozilla.org/en-US/docs/Learn/Server-side/Django/Testing

For any further doubts and queries, feel free to join the community and ask there: https://discord.gg/Ek9q45ZjAv

**Comment by nayaldivya** [comment]
Hi @garg3133, can you please assign this issue to me

**Comment by garg3133** [comment]
Sure @nayaldivya!

**Comment by garg3133** [comment]
@nayaldivya You may also refer to `IndexViewTests` [here](https://github.com/garg3133/fossee/blob/master/roomslotbooking/home/tests/test_views.py) if this is the first time you are writing tests and want to know more about how to write these.

**Comment by subhangi2731** [comment]
can you please assign this to me?

**Comment by garg3133** [comment]
@subhangi2731 Please comment on one issue only which you want to work on and I'll assign that to you.

**Comment by somya51p** [comment]
Hey @garg3133 sir, I wish to contribute to this issue under GSSOC. Please assign it to me if it is unassigned.

**Comment by subhangi2731** [comment]
please assign me this too. Due to my health problems I have got very behind. I need to cover up

**Comment by AJAYSHARMA2012** [comment]
> please assign me this too. Due to my health problems I have got very behind. I need to cover up

@subhangi2731 I am assigning you this issue

**Comment by subhangi2731** [comment]
I will send a pr by tomorrow @AJAYSHARMA2012

**Comment by subhangi2731** [comment]
@AJAYSHARMA2012 @garg3133 I am writing tests for login_signup view

But the below is giving me an error django.urls.exceptions.NoReverseMatch: Reverse for 'accounts' not found. 'accounts' is not a valid view function or pattern name.
 def test_view_url_accessible_by_name(self):
        response = self.client.get(reverse('accounts'))
        self.assertEqual(response.status_code, 200

**Comment by subhangi2731** [comment]
but I am getting an error please help me in this

**Comment by garg3133** [comment]
@subhangi2731 `accounts` represents the app name, not a URL. To get the reverse for `login_signup` view, you should write `accounts:login_signup` instead.

**Comment by subhangi2731** [comment]
@garg3133 AttributeError: Manager isn't available; 'auth.User' has been swapped for 'accounts.User'
I am getting this error
And, If I replace auth.models with defined User in the app, I get the error AssertionError: 'AnonymousUser' != 'testuser1'
When I pass login = self.client.login(email='abc@gmail.com')

**Comment by garg3133** [comment]
@subhangi2731 Getting AnonymousUser means that the user is not logged in. You need to provide the password too while logging in.

**Comment by subhangi2731** [comment]
@garg3133 test_user1 = User.objects.create_user(username='testuser1', password='1X<ISRUkw+tuK')
TypeError: create_user() got an unexpected keyword argument 'username' why is this coming ?? please tell

**Comment by garg3133** [comment]
@subhangi2731 Try using `email` instead of `username` (as there is no `username` field in the custom user model, `email` field is used as username).

**Comment by subhangi2731** [comment]
@garg3133 def test_redirect_if_logged_in_and_profile_complete(self):
        #  Login the User 1 (having complete profile)
        login = self.client.login(email='testuser1@gmail.com')
        response = self.client.get(reverse('accounts:login_signup'))

        # Check it redirects correctly to dashboard
        self.assertEqual(response.status_code, 200)
        self.assertRedirects(response, reverse('home:dashboard'))

In this test this AssertionError: 200 != 302 is showing
It is not redirecting please help me

**Comment by garg3133** [comment]
@subhangi2731 You need to enter the password as well in `self.client.login()` to login the client.

**Comment by subhangi2731** [comment]
@garg3133 please help me in this I have already invested many days in this issue I face this error
def test_view_login_with_correct_data(self):
        response = self.client.post(reverse('accounts:login_signup'), {
            'email' : 'testuser1@gmail.com',
            'password' : '1X<ISRUkw+tuK',
            'submit' : 'login'
        })
        # print(response)
        # Check it redirects correctly to dashboard
        self.assertEqual(response.status_code, 302)
        self.assertRedirects(response, reverse('accounts/login_signup.html'))
       self.assertEqual(response.status_code, 302)
      AssertionError: 200 != 302

**Comment by garg3133** [comment]
@subhangi2731 Have you created the user before logging in? If yes, is the `active` field of User set to true (without this, the user won't be able to log in)? If you've not done any of this, then the status code will be 200 only and not 302 as the user will be served the same template with corresponding errors.

As you can see from the `login_signup` implementation, it first checks if the `active` field of user is `True` or not. If not, the user is served the same template with error. If the user is active, then it checks if the user has a profile. If not, the user is redirected to the `complete_profile` page and so on...

Also, in the third last line, there should be `accounts:login_signup` inside reverse.

**Comment by subhangi2731** [comment]
@garg3133 Yes, I have created the complete user profile with everything correct, but am still getting the error:

in test_view_login_with_correct_data
    self.assertEqual(response.status_code, 302)
AssertionError: 200 != 302




def setUpTestData(cls):
        # Create a user
        test_user1 = User.objects.create_user(email='testuser1@gmail.com', password='1X<ISRUkw+tuK')

        test_user1.save()

        # Complete profile of first user
        test_user1.first_name = 'test'
        test_user1.last_name = 'user'
        test_user1.is_active = True
        test_user1.auth = False
        test_user1.save()
        test_user1_profile = Profile.objects.create(
            user = test_user1,
            gender = 'M',
            alt_email = 'kajn@lfknf.com',
            profile_image = 'fesse.JPEG',
            street_address1 = 'awdwdawd',
            street_address2 = 'awdawdawd',
            contact_no = '9999985641',
            city = 'Houston',
            state = 'Texas',
            pincode = 98743
        )

    def test_view_url_exists_at_desired_location(self):
        response = self.client.get('')
        self.assertEqual(response.status_code, 200)
           
    def test_view_url_accessible_by_name(self):
        response = self.client.get(reverse('accounts:login_signup'))
        self.assertEqual(response.status_code, 200)
 

    def test_view_login_with_correct_data(self):
        response = self.client.post(reverse('accounts:login_signup'), {
            'email' : 'testuser1@gmail.com',
            'password' : '1X<ISRUkw+tuK',
            'submit' : 'login'
        })
        # Check it redirects correctly to dashboard
        self.assertEqual(response.status_code, 302)
        self.assertRedirects(response, reverse('accounts:complete_profile'))

**Comment by subhangi2731** [comment]
@garg3133 please check this

**Comment by garg3133** [comment]
@subhangi2731 You have set `is_active=True` and you've also created a profile for the user, but you've set `auth=True`. If you look at the code, in this case, the same template will be served by the server with an error saying that the user is not yet authenticated by the admin (and hence the 200 status code).

**Comment by garg3133** [comment]
Resolved in #275.
