### ISSUE TITLE
Clicking on student name should open student profile

### ISSUE THREAD

**Issue by garg3133** [garg3133/JagratiWebApp#80]
On clicking on the student name (appearing anywhere throughout the app), the student's profile should open **in a new tab**.

If I remember correctly, right now student names appear in two places, one on student attendance page (`/students/attendance/`) and other on the dashboard (`'/dashboard/`). The student profile can be found at `/students/profile/<user_id>/`.

Solving this issue requires a basic understanding of Django.

For any further doubts and queries, feel free to join the community and ask there: https://discord.gg/Ek9q45ZjAv

**Comment by sakshikhachane** [comment]
@garg3133 I would like to work on this issue.

**Comment by garg3133** [comment]
Sure @sakshikhachane!

**Comment by Aniket118** [comment]
I would like to work on this issue! @garg3133

**Comment by garg3133** [comment]
Sure @Aniket118, go on!

**Comment by Shivam-Shandilya1** [comment]
Can I work on this issue?

**Comment by garg3133** [comment]
Sure @Shivam-Shandilya1, you can work on this. Assigning you the issue.

**Comment by kagritu** [comment]
I would like to work on it as a part of GSSOC'21, so please assign that to me.

**Comment by garg3133** [comment]
Sure @kagritu, as there is no progress from @Shivam-Shandilya1 yet, you can take this issue.

**Comment by kagritu** [comment]
Thank you.

**Comment by garg3133** [comment]
Any progress @kagritu?

**Comment by kagritu** [comment]
Yes, I am working on it.

**Comment by ThumarHarsh** [comment]
@garg3133  can I work on this?... I have already added the same functionality in the volunteer's module..so I'm experienced in this.

**Comment by garg3133** [comment]
Sorry @kagritu, but it's been over a week since you took this issue. I'll wait for one more day (today) and if I don't see any progress, I'll assign it to someone else.

**Comment by kagritu** [comment]
There was exam going on in our college, so i couldn't work on it much.
Sorry about that.

**Comment by garg3133** [comment]
What is the status of this now @kagritu?

**Comment by kagritu** [comment]
I am sorry, but i am not able to solve the issue

**Comment by garg3133** [comment]
What is the problem you're facing?

**Comment by kagritu** [comment]
Actually i don't know much about django, i thought i could solve it using python, i am sorry about that.

**Comment by garg3133** [comment]
Okay, no problem then @kagritu! @ThumarHarsh would you like to work on it?

**Comment by ThumarHarsh** [comment]
Yes @garg3133 i would like to solve this

**Comment by garg3133** [comment]
That's great @ThumarHarsh, assigning you the issue.

**Comment by SnehaVeerakumar** [comment]
I would like to contribute to this issue. If assigned, 2 to 5 days is needed for me to complete it. @garg3133

**Comment by garg3133** [comment]
Sure @SnehaVeerakumar, go ahead with the issue. Assigning it to you.

**Comment by harshakhmk** [comment]
Is the issue still needs to be addressed, if yes I can work on it to get my first open-source contribution

**Comment by garg3133** [comment]
@Subhangini Are you still interested to work on this issue?

@harshakhmk If Subhangini doesn't reply, I'll assign this issue to you.

**Comment by Subhangini** [comment]
Yes I would like to work once you assign me

**Comment by Subhangini** [comment]
Due to some reasons, I started late sorry for that, but I cannot find these files where I have to make the changes, I got the Student folder but not the other ones and I also tried the app but was unable to do so. Is the app working? Because after login I was, again and again, asked to log in? Is there any issue?

**Comment by garg3133** [comment]
@Subhangini You need to make the changes on the Student Attendance page and dashboard (where students' name will appear after you take the attendance).

You can take a look at PR #134, which resolves a similar issue, for reference.

I don't think there's any issue with the login functionality of the app (it's working fine for me). Can you share some screenshots of the problem you're facing?

**Comment by Subhangini** [comment]
![image](https://user-images.githubusercontent.com/68437435/118845491-72550f80-b8e9-11eb-9655-e6e0fae8ebe3.png)

**Comment by Subhangini** [comment]
![image](https://user-images.githubusercontent.com/68437435/118846243-28205e00-b8ea-11eb-8548-31968fd3f11c.png)


>I don't think there's any issue with the login functionality of the app (it's working fine for me). Can you share some screenshots of the problem you're facing?

this is the issue I am facing

**Comment by garg3133** [comment]
Ohh for this you need to authenticate the newly created user using the link that must have been printed on your terminal (like you must have done for verifying your email the first time you created the account.

Alternatively, you can go to the admin portal (localhost:8000/admin) and login their with your superuser credentials. Then go to User -> select the user and tick the `Auth` field at the bottom and save it. You'll be able to login into the app after doing so.

**Comment by Subhangini** [comment]
> Ohh for this you need to authenticate the newly created user using the link that must have been printed on your terminal (like you must have done for verifying your email the first time you created the account.
> 
> Alternatively, you can go to the admin portal (localhost:8000/admin) and login their with your superuser credentials. Then go to User -> select the user and tick the `Auth` field at the bottom and save it. You'll be able to login into the app after doing so.

I will try this

**Comment by Subhangini** [comment]
Sorry Due to some reasons I am unable to solve this. Thank you @garg3133  for clearing my doubts.

**Comment by harshakhmk** [comment]
Can I work on this, I can contribute @priyansh3133

**Comment by garg3133** [comment]
Yeah sure, @harshakhmk, go ahead!

**Comment by harshakhmk** [comment]
Placing the profile URL in the HTML files would solve right?

**Comment by garg3133** [comment]
Yes

**Comment by garg3133** [comment]
Resolved in #278.
