### ISSUE TITLE
Clicking on volunteer name should open volunteer profile

### ISSUE THREAD

**Issue by garg3133** [garg3133/JagratiWebApp#81]
On clicking on the volunteer name (appearing anywhere throughout the app), the volunteer's profile should open **in a new tab**.

If I remember correctly, right now volunteer names appear in three places, one on the volunteer attendance page (`/volunteers/attendance/`), on the volunteers list page (`/volunteers/list/`), and last on the dashboard (`'/dashboard/`). You need to assign yourself a designation of `Math Convener` to view volunteer attendance on the Dashboard.

The volunteer profile can be found at `/volunteers/profile/<user_id>/`.

Solving this issue requires a basic understanding of Django.

For any further doubts and queries, feel free to join the community and ask there: https://discord.gg/Ek9q45ZjAv

**Comment by sakshikhachane** [comment]
@garg3133 I would also like to work on this issue.

**Comment by garg3133** [comment]
I'll assign this to you once you complete #80. Till then, this issue is open for others.

**Comment by tanya162** [comment]
I would like to work on this issue

**Comment by garg3133** [comment]
Sure @tanya162, go ahead! Assigning you the issue.

**Comment by Aniket118** [comment]
I would like to work on this issue! @garg3133

**Comment by Shivam-Shandilya1** [comment]
Can I work on this Issue?

**Comment by Haneesha123** [comment]
Hi, I am a GSSOC'21 participant and I have experience in Django. Can you assign me to this issue? @garg3133

**Comment by Haneesha123** [comment]
Okay. I would like to take up issue #34  @garg3133

**Comment by garg3133** [comment]
@Haneesha123 Just comment on that issue and I'll assign it to you.

**Comment by ThumarHarsh** [comment]
Hi, I am a GSSOC'21 participant and I have experience in Django. Can you assign me to this issue? @garg3133

**Comment by garg3133** [comment]
Sure @ThumarHarsh, as @Shivam-Shandilya1 is not responding, you can take up this issue. Assigning it to you.

**Comment by ThumarHarsh** [comment]
how can i  assign myself as s designation of Math Convener to view volunteer attendance on the Dashboard.@garg3133

**Comment by ThumarHarsh** [comment]
@garg3133, now it works perfect,issue solved completely
