### ISSUE TITLE
Take student attendance using AJAX

### ISSUE THREAD

**Issue by garg3133** [garg3133/JagratiWebApp#82]
Right now, for taking the student attendance, we need to mark all the present students as present (by ticking the corresponding checkbox) on `/students/attendance/` page and then submit the form. The way it works is, it first marks all the students of the classes for which the attendance was submitted as absent and then marks the students for which checkbox was ticked as present.

But there's a problem in this approach, if two people take attendance of two different classes at the same time, the app will go into race condition and the attendance submitted by only one of them will be saved to database.

To resolve this issue, we need to take student attendance using AJAX where the attendance of the student will be marked and saved to the database just by ticking the checkbox, one student at a time and thus we don't need to submit the form to take attendance.

Solving this issue requires intermediate knowledge of Javascript (AJAX) and Django.

For any further doubts and queries, feel free to join the community and ask there: https://discord.gg/Ek9q45ZjAv

**Comment by garg3133** [comment]
@sagarpandyansit If you're interested, you may take up this issue as by now you've gained a good knowledge of AJAX and this will be a good challenge to level it up.

**Comment by sagarpandyansit** [comment]
Sure, @garg3133. It would be a good learning experience with you. You can assign it to me.

**Comment by sagarpandyansit** [comment]
@garg3133, I found `ajax/attendance` URL in the students `urls.py` file as well as `view` for that. Has this issue already been resolved? Kindly check.

**Comment by garg3133** [comment]
@sagarpandyansit No, that is for fetching the student list according to class range selected in dropdown. You can change these to `ajax_attendance_fetch_students`.
