### ISSUE TITLE
Connect button on phone not shown completely 

### ISSUE THREAD

**Issue by schmelto** [garg3133/JagratiWebApp#84]
![Screenshot_20210201_231039_com.android.chrome~3.jpg](https://user-images.githubusercontent.com/30869493/106524473-ec9c8800-64e2-11eb-9c4d-1ab1ef6b2234.jpg)

**Comment by garg3133** [comment]
Thanks for raising the issue @schmelto!

Actually, we had already fixed this issue but it was not deployed on Heroku. I've just deployed all the recent changes to heroku and this issue has been fixed now.

Cheers!!
