### ISSUE TITLE
Add Github Actions

### ISSUE THREAD

**Issue by Aayush-hub** [garg3133/JagratiWebApp#86]
Add Github actions for enhancement of project

**Comment by garg3133** [comment]
Can you please explain in more details what exactly you are proposing. I see no use case of GitHub Actions in this project as of now. Maybe we'll need GitHub Actions later once the tests are developed for the project.

**Comment by Aayush-hub** [comment]
@garg3133 We can add First Interaction bot for first time contributors to this project to greet them with a message,  when they raise any issue or make any pull request solving any issue. This makes project more attractive for contributors.

**Comment by garg3133** [comment]
@Aayush-hub There's already an issue open for this #56. You can ask the assignee of that issue and if he's not working, you can work on that issue.
