### ISSUE TITLE
centralized "Vision" and "Mission" text part in the about us section

### ISSUE THREAD

**Issue by Abhijay007** [garg3133/JagratiWebApp#87]
Currently, on the website, the "vision" and "mission" text part in the "About us" section (for the web view) is not aligned in the center with respect to the given picture.

***before***
![jagriti-vis](https://user-images.githubusercontent.com/64387054/106883046-71ff8280-6705-11eb-9126-c3d659f29124.PNG)

***after***
![jagriti-vis-after](https://user-images.githubusercontent.com/64387054/106883119-8e9bba80-6705-11eb-98c6-d509d738224e.PNG)

**Comment by garg3133** [comment]
Hey @Abhijay007, thanks for raising this issue! But this is actually intentional and we don't want to change that.
