### ISSUE TITLE
Take volunteer attendance using AJAX

### ISSUE THREAD

**Issue by garg3133** [garg3133/JagratiWebApp#90]
Right now, for taking the volunteer attendance, we mark all the present volunteers as present (by ticking the corresponding checkbox) on `/volunteers/attendance/` page and then submit the form. On submitting the form, the backend first marks all the volunteers scheduled for that day as absent and then marks the volunteers for whom checkbox was ticked as present.

Also, if there are some extra volunteers on that day, we can add their roll_no by clicking `Add more` button on the page and if such a volunteer exists, he/she will also be added to the attendance.

What we want now is instead of marking all the volunteers as present and then submitting the form, the volunteers should be marked as present/absent using AJAX (that is, they will be marked as present/absent on backend also as soon as we tick/untick the corresponding checkbox and thus there will be no need of submitting any form). 

So, this issue has two parts:
- [x] Mark volunteer attendance using AJAX.
- [x] Mark attendance of extra volunteers who are not already present in the list. (Put a single text input field in the Name column and `Add` button in checkbox column, instead of the `Add more` button. Whenever `Add` button is clicked after writing the roll_no in input field, that volunteer holding that roll_no should be added to the list using AJAX with his/her attendance already marked.)

For any further doubts and queries, feel free to join the community and ask there: https://discord.gg/Ek9q45ZjAv

(Implementation in #113 might help with this issue.)

**Comment by micksharma** [comment]
I want to work on this issue.

**Comment by subhangi2731** [comment]
can you please assign me this?

**Comment by sagarpandyansit** [comment]
@garg3133, Is this the same as student's attendance?

**Comment by garg3133** [comment]
@sagarpandyansit Yes, it's pretty much the same with the only difference of the feature of adding extra volunteers to the attendance which are not a part of schedule.

**Comment by sagarpandyansit** [comment]
@garg3133, then there should be 2 different issues, isn't it? One is to add volunteers and the other one is to mark the attendance.

**Comment by garg3133** [comment]
@sagarpandyansit Adding attendance of an extra volunteer is just a continuation work of "Marking the attendance using AJAX" and can only be done after the latter work is complete. Instead of a separate issue, this issue can have two parts where the second part can only be done after the first is complete.

**Comment by garg3133** [comment]
Edited the issue with the two tasks which can be done in two separate PRs.

**Comment by sagarpandyansit** [comment]
I would like to work on this issue but, I could not be able to work on this right now due to the end sem exam. You may assign this to anyone, else I will start working on this after 3rd April.

**Comment by pallavi00021** [comment]
@garg3133  can I start working on this issue?? I'm gssoc'21 participant.

**Comment by garg3133** [comment]
Yes @pallavi00021, please go ahead! Assigning you the issue.

**Comment by sagarpandyansit** [comment]
@garg3133, @pallavi00021 Any update on this?

**Comment by garg3133** [comment]
@sagarpandyansit I don't think there's any progress on this issue (she has not even forked the repository). So you can go ahead with the issue. Assigning it to you.

**Comment by garg3133** [comment]
@sagarpandyansit Use `Fixes: #90` in your PR description, so that the bot can track the PR for this issue.

**Comment by sagarpandyansit** [comment]
Okay. No problem. In the meantime, I will try to complete the rest of the work. best of luck for your exams and projects.

**Comment by garg3133** [comment]
Second part resolved in commits starting with 56c2381.
