### ISSUE TITLE
A Linter for Python

### ISSUE THREAD

**Issue by vybhav72954** [garg3133/JagratiWebApp#97]
As we are using Django as our backend, I believe it would be a good idea to have a Linter for Python.

This will help in enforcing guidelines, code quality, and documentation at the same time ensuring that no improper or vulnerable code has been pushed in the Repo.

**Comment by garg3133** [comment]
That would be a good idea. You can move forward with this. Assigning you the issue.

**Comment by vybhav72954** [comment]
Was just wondering, as am a participant in Script WInter of Code, can Labels be assigned though?

**Comment by garg3133** [comment]
Yeah, sure!

**Comment by vybhav72954** [comment]
And one last quetion

Whcih linter would you prefer?

- pyLint (Best overall, but strict)
- Black (Less strict)
- flake8 (Most beginner-friendly)

I would recommend pyLint, as we can change the threshold

**Comment by vybhav72954** [comment]
This is awkward, I just noticed you guys are participating in `Mexili ` as well, can you put that label as well 😅

**Comment by garg3133** [comment]
I think flake8 will be good for now as I haven't used any fixed coding standard while writing this app so there may be many inconsistencies throughout the application and it won't be a good idea to enforce strict standards at this point. 

> This is awkward, I just noticed you guys are participating in Mexili as well, can you put that label as well 😅

Sure.

**Comment by vybhav72954** [comment]
I understand your point, but take this as a suggestion, Even if there are no super strict standards here (which means no pylint), still black is a better choice than flake8.

or even better, flake8 after black (I will leave this for you to decide) meanwhile I will start with the environment configuration.

PS- We can update in future now the less, so not a big probelm

**Comment by garg3133** [comment]
Well, I don't have much idea about the lining as of now so you can decide according to your experience which linter will be best in our case (we just don't want to enforce very strict coding standards for now).

**Comment by vybhav72954** [comment]
Sure i will ensure that, secodly, I will ensure that you can configure the linter from your side as well in order to make it more liniant or strict as per your preferences, would be opening the PR asap.
